// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// API Description
    /// </summary>
    public partial interface IZoomAPI : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// The meeting ID
        /// </summary>
        int MeetingId { get; set; }

        /// <summary>
        /// The meeting type. Possible values include: 'scheduled', 'live',
        /// 'upcoming'
        /// </summary>
        string Type { get; set; }

        /// <summary>
        /// Current page number of returned records
        /// </summary>
        int? PageNumber { get; set; }

        /// <summary>
        /// The number of records returned within a single API call
        /// </summary>
        int? PageSize { get; set; }

        /// <summary>
        /// The user ID or email address
        /// </summary>
        string UserId { get; set; }


        /// <summary>
        /// List meetings
        /// </summary>
        /// <remarks>
        /// List meetings for a user
        /// </remarks>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<MeetingList>> MeetingsWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create a meeting
        /// </summary>
        /// <remarks>
        /// Create a meeting for a user &lt;aside&gt;The expiration time of
        /// start_url is two hours. But for API users, the expiration time is
        /// 90 days.&lt;/aside&gt;
        /// </remarks>
        /// <param name='body'>
        /// Meeting object
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<MeetingInfoCreated,MeetingCreateHeaders>> MeetingCreateWithHttpMessagesAsync(Meeting body, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
