// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for ZoomAPI.
    /// </summary>
    public static partial class ZoomAPIExtensions
    {
            /// <summary>
            /// List meetings
            /// </summary>
            /// <remarks>
            /// List meetings for a user
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static MeetingList Meetings(this IZoomAPI operations)
            {
                return operations.MeetingsAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// List meetings
            /// </summary>
            /// <remarks>
            /// List meetings for a user
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MeetingList> MeetingsAsync(this IZoomAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.MeetingsWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a meeting
            /// </summary>
            /// <remarks>
            /// Create a meeting for a user &lt;aside&gt;The expiration time of start_url
            /// is two hours. But for API users, the expiration time is 90
            /// days.&lt;/aside&gt;
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// Meeting object
            /// </param>
            public static MeetingInfoCreated MeetingCreate(this IZoomAPI operations, Meeting body)
            {
                return operations.MeetingCreateAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a meeting
            /// </summary>
            /// <remarks>
            /// Create a meeting for a user &lt;aside&gt;The expiration time of start_url
            /// is two hours. But for API users, the expiration time is 90
            /// days.&lt;/aside&gt;
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// Meeting object
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MeetingInfoCreated> MeetingCreateAsync(this IZoomAPI operations, Meeting body, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.MeetingCreateWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
