using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Crochik.Logging;
using Crochik.Mongo;
using Microsoft.Extensions.Logging;
using PI.Shared.Constants;
using PI.Shared.Models;
using PI.Shared.Services;

namespace Services;

public class LoadServiceAppointmentOnChangeProcessor : LoadObjectOnChangeProcessor<SalesforceCustomObject>, IOnServiceAppointmentChangeProcessor
{
    public override string ObjectType => "sf_ServiceAppointment";
    
    private readonly ServiceAppointmentConverter _converter;
    private readonly LoadLeadOnChangeProcessor _leadLoader;

    public LoadServiceAppointmentOnChangeProcessor(
        ILogger<LoadServiceAppointmentOnChangeProcessor> logger, 
        MongoConnection connection, 
        ObjectTypeService objectTypeService, 
        SalesforceService salesforceService,
        ServiceAppointmentConverter converter,
        LoadLeadOnChangeProcessor leadLoader
        ) : base(logger, connection, objectTypeService, salesforceService)
    {
        _converter = converter;
        _leadLoader = leadLoader;
    }

    protected override async Task<IFlowObject> ImportObjectAsync(ImportObject options)
    {
        var appointment = default(Appointment);

        // check if the Appointment created by pi has already integration
        // if not, we are probably processing the event from Salesforce generated by the creation of the appointment by PI
        // and it has not updated it yet with the integration info
        if (options.Source.TryGetProperty("PIId__c", out string appointmentIdStr) && Guid.TryParse(appointmentIdStr, out var appointmentId))
        {
            using var scope = _logger.AddScope(new
            {
                AppointmentId = appointmentId,
            });

            _logger.LogInformation("Appointment was created by PI");

            appointment = await _connection.Filter<Appointment>()
                .Eq(x => x.AccountId, options.Context.AccountId.Value)
                .Eq(x => x.Id, appointmentId)
                .FirstOrDefaultAsync();

            if (appointment == null)
            {
                _logger.LogError("Couldn't load Appointment");
                return null;
            }

            var integration = appointment.Integrations?.FirstOrDefault(x => x.IntegrationId == IntegrationIds.Salesforce && x.ExternalId == options.Source.ExternalId);
            if (integration == null)
            {
                _logger.LogInformation("Appointment does not include Integration yet, ignore event");
                return null;
            }
        }

        appointment ??= await _connection.Filter<Appointment>()
            .Eq(x => x.AccountId, options.Context.AccountId.Value)
            .ElemMatchBuilder(
                x => x.Integrations,
                q => q
                    .Eq(x => x.IntegrationId, IntegrationIds.Salesforce)
                    .Eq(x => x.ExternalId, options.Source.ExternalId)
            )
            .FirstOrDefaultAsync();

        if (appointment != null)
        {
            appointment = await _converter.UpdateAppointmentRefsAsync(options.Context, options.Source, appointment);
            await UpdateLeadWithAppointmentAsync(options.Context, options.Source, appointment);
            return appointment;
        }

        _logger.LogInformation("Appointment with {ExternalId} not found, try to find lead w/o it", options.Source.ExternalId);

        // try to find lead (using account)
        if (!options.Source.TryGetProperty("AccountId", out string sfAccountId))
        {
            _logger.LogInformation("Missing AccountId for ServiceAppointment, can't do anything...");
            return appointment;
        }

        var lead = await _leadLoader.FindLeadBySfAccountIdAsync(options.Context, sfAccountId);
        if (lead != null)
        {
            _logger.LogInformation("Mark {LeadId} as converted", lead.Id);
            await _leadLoader.MarkLeadAsConvertedAsync(options.Context, lead);
        }

        return await ImportAppointmentAsync(options.Context, lead, options.Source);
    }


    private async Task<Appointment> ImportAppointmentAsync(IEntityContext context, Lead lead, SalesforceCustomObject source)
    {
        if (lead == null)
        {
            _logger.LogInformation("Couldn't find/import Lead, can't import appointment");
            return null;
        }

        return await _converter.CreateAsync(context, source);
    }
    
    // - Id
    // - Status
    // - SchedStartTime
    // - SystemModstamp
    // - AppointmentNumber
    // - IsDeleted
    private async Task<Lead> UpdateLeadWithAppointmentAsync(IEntityContext context, SalesforceCustomObject source, Appointment appointment)
    {
        using var scope = _logger.AddScope(new
        {
            AppointmentId = appointment.Id,
            appointment.LeadId,
            source.ObjectType,
            source.ExternalId,
            source.Id,
        });

        _logger.LogInformation("Update Appointment");

        var lead = await _connection.Filter<Lead>()
            .Eq(x => x.AccountId, context.AccountId)
            .Eq(x => x.Id, appointment.LeadId)
            .IncludeField(x => x.ConvertedOn)
            .IncludeField(x => x.LastModifiedOn)
            .IncludeField(x => x.NextAppointmentId)
            .IncludeField(x => x.AssignedEntityId)
            .FirstOrDefaultAsync();

        if (lead == null)
        {
            _logger.LogError("Couldn't load lead");
            return null;
        }

        var nextAppointmentId = lead.NextAppointmentId != appointment.Id &&
                                !appointment.CancelledOn.HasValue &&
                                appointment.IsActive &&
                                appointment.Start > DateTime.UtcNow ?
            appointment.Id :
            default(Guid?);

        if (lead.ConvertedOn.HasValue && nextAppointmentId.HasValue)
        {
            // nothing to do 
            // ...
            _logger.LogInformation("Lead has already been converted and has {NextAppointmentId}, nothing to do", lead.NextAppointmentId);
            return lead;
        }

        if (!source.TryGetProperty<DateTime>("CreatedDate", out var convertedOn) &&
            !source.TryGetProperty("SystemModstamp", out convertedOn))
        {
            convertedOn = DateTime.UtcNow;
        }

        var modifiedFields = new Dictionary<string, object>();
        
        var updateLeadQuery = _connection.Filter<Lead>()
            .Eq(x => x.Id, lead.Id)
            .Eq(x => x.LastModifiedOn, lead.LastModifiedOn)
            .Update
            .Set(x => x.LastModifiedOn, DateTime.Now)
            .Set(x => x.LastActor, context.Actor());

        if (!lead.ConvertedOn.HasValue)
        {
            _logger.LogInformation("Set {ConvertedOn}", convertedOn);
            updateLeadQuery.Set(x => x.ConvertedOn, convertedOn);
            
            modifiedFields.Add(nameof(Lead.ConvertedOn), convertedOn);
        }

        if (nextAppointmentId.HasValue)
        {
            _logger.LogInformation("Set {NextAppointmentId}: {Start} {AssignedEntityId}", appointment.Id, appointment.Start, appointment.EntityId);
            updateLeadQuery
                .Set(x => x.NextAppointmentId, appointment.Id)
                .Set(x => x.AssignedEntityId, appointment.EntityId)
                ;
            
            modifiedFields.Add(nameof(Lead.NextAppointmentId), appointment.Id);
            modifiedFields.Add(nameof(Lead.AssignedEntityId), appointment.EntityId);
        }

        var modifiedLead = await updateLeadQuery.UpdateAndGetOneAsync();
        if (modifiedLead == null)
        {
            _logger.LogInformation("Failed to update {LeadId}, it has been updated since {LastModifiedOn}", lead.Id, lead.LastModifiedOn);
            return null;
        }

        await _objectTypeService.FireObjectUpdatedAsync(context, modifiedLead, modifiedFields, evt =>
        {
            evt.Description = "Appointment updated with Salesforce changes";
            evt.SetRefValue(nameof(Integration), IntegrationIds.Salesforce);
            evt.SetMetaValue(nameof(Integration), IntegrationIds.GetName(IntegrationIds.Salesforce));
            evt.SetRefValue(nameof(Appointment), nextAppointmentId);
        });

        _logger.LogInformation("{LeadId} updated", modifiedLead.Id);

        return modifiedLead;
    }
    
}