using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Crochik.Extensions;
using Crochik.Mongo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using PI.Shared.Controllers;
using PI.Shared.Exceptions;
using PI.Shared.Form.Models;
using PI.Shared.Models;
using PI.Shared.Models.Expressions;
using PI.Shared.Services;

namespace Controllers;

[Route("/api/v1/[controller]")]
[Authorize("default")]
public class SnapshotController : APIController
{
    private readonly MongoConnection _connection;
    private readonly ObjectTypeService _objectTypeService;

    public SnapshotController(MongoConnection connection, ObjectTypeService objectTypeService)
    {
        _connection = connection;
        _objectTypeService = objectTypeService;
    }

    /// <summary>
    /// Get dataView from snapshot data
    /// somewhat of a hack and can't do much with it 
    /// </summary>
    [Authorize("default")]
    [HttpPost("/api/v1/[controller]({id:guid})/DataView")]
    [Produces("text/csv", "application/json")]
    public async Task<IDataViewResponse> DataViewAsync([FromRoute] Guid id, [FromBody] DataViewRequest request)
    {
        var snapshot = await _connection.Filter<Snapshot>()
            .Eq(x => x.AccountId, Context.AccountId.Value)
            .Eq(x => x.CreatedById, Context.UserId.Value)
            .FirstOrDefaultAsync();

        request.Criteria = (request?.Criteria ?? Enumerable.Empty<Condition>())
            .Where(x => x.FieldName != nameof(SnapshotData.SnapshotId))
            .Append(Condition.Eq(nameof(SnapshotData.SnapshotId), id))
            .ToArray();

        // add snapshotId filter to filterForm so the builder will allow to filter it
        snapshot.DataView.FilterForm.Fields = new FormField[]
        {
            new ReferenceField
            {
                Name = nameof(SnapshotData.SnapshotId),
                Label = "Snapshot",
                ReferenceFieldOptions = new ReferenceFieldOptions
                {
                    ObjectType = snapshot.ObjectType,
                },
                Enable = new[] { "false" },
            }
        };

        return await DataViewResponseBuilder
            .New(_connection, Context, request, snapshot)
            .BuildAsync();
    }

    [Authorize("default")]
    [HttpPost("/api/v1/[controller]/Fields/Lookup")]
    public async Task<IEnumerable<ReferenceValue>> LookupByIdAsync(DataViewRequest request)
    {
        var condition = request?.Criteria?.FirstOrDefault(x => x.FieldName == Model.IdFieldName);
        if (condition == null) throw new BadRequestException("Missing criteria");
        if (!condition.Value.TryToParseObjectId(out var id)) throw new BadRequestException("Invalid criteria");

        var snapshot = await _connection.Filter<Snapshot>()
            .Eq(x => x.AccountId, Context.AccountId.Value)
            .Eq(x => x.Id, id)
            .FirstOrDefaultAsync();

        if (snapshot?.DataView?.Fields == null) return Enumerable.Empty<ReferenceValue>();

        var options = snapshot.DataView.Fields
            .OrderBy(x => x.Label ?? x.Name)
            .Select(x => new ReferenceValue
            {
                Id = x.Name,
                Value = x.Label ?? x.Name,
                Description = x.Description,
            });

        if (request.Criteria.TryGetEqCondition(Condition.LookupId, out var lookupCondition) && lookupCondition.Value is string fieldName)
        {
            var match = options.FirstOrDefault(x => x.Id == fieldName);
            return match == null ? Enumerable.Empty<ReferenceValue>() : match.AsEnumerable();
        }

        return options;
    }

    /// <summary>
    /// Get field names that will be generated by creating a snapshot of this appView
    /// (e.g. add prefix "Properties|" to existing fields :) )
    /// </summary>
    /// <param name="request"></param>
    /// <returns></returns>
    /// <exception cref="BadRequestException"></exception>
    [Authorize("default")]
    [HttpPost("/api/v1/[controller]/AppDataView/Fields/Lookup")]
    public async Task<IEnumerable<ReferenceValue>> LookupByAppDataViewAsync(DataViewRequest request)
    {
        var condition = request?.Criteria?.FirstOrDefault(x => x.FieldName == nameof(Snapshot.AppDataViewId));
        if (condition == null) throw new BadRequestException("Missing criteria");
        if (!condition.Value.TryToParseObjectId(out var id)) throw new BadRequestException("Invalid criteria");

        var appDataView = await _connection.Filter<AppDataView>()
            .Eq(x => x.AccountId, Context.AccountId.Value)
            .Eq(x => x.Id, id)
            .FirstOrDefaultAsync();

        if (appDataView?.Fields == null) return Enumerable.Empty<ReferenceValue>();

        var objectType = await _objectTypeService.GetAsync(new AccountContext(appDataView.AccountId), appDataView.ObjectType);
        if (objectType == null) throw NotFoundException.New("Object type not found ");

        var fieldNames = appDataView.Fields.ToHashSet();
        var options = objectType.Fields
            .Where(x => fieldNames.Contains(x.Key))
            .Select(x => x.Value.Field)
            .OrderBy(x => x.Label ?? x.Name)
            .Select(x => new ReferenceValue
            {
                Id = $"Properties|{x.Name}",
                Value = x.Label ?? x.Name,
                Description = x.Description,
            });

        if (request.Criteria.TryGetEqCondition(Condition.LookupId, out var lookupCondition) && lookupCondition.Value is string fieldName)
        {
            var match = options.FirstOrDefault(x => x.Id == fieldName);
            return match == null ? Enumerable.Empty<ReferenceValue>() : match.AsEnumerable();
        }

        return options;
    }
}