// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Meeting object
    /// </summary>
    public partial class Meeting : Session
    {
        /// <summary>
        /// Initializes a new instance of the Meeting class.
        /// </summary>
        public Meeting()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Meeting class.
        /// </summary>
        /// <param name="topic">Meeting topic</param>
        /// <param name="type">Meeting Type</param>
        /// <param name="startTime">Meeting start time. When using a format
        /// like "yyyy-MM-dd'T'HH:mm:ss'Z'", always use GMT time. When using a
        /// format like "yyyy-MM-dd'T'HH:mm:ss", you should use local time and
        /// you will need to specify the time zone. Only used for scheduled
        /// meetings and recurring meetings with fixed time.</param>
        /// <param name="duration">Meeting duration (minutes). Used for
        /// scheduled meetings only</param>
        /// <param name="timezone">Timezone to format start_time. For example,
        /// "America/Los_Angeles". For scheduled meetings only. Please
        /// reference our [timezone](#timezones) list for supported timezones
        /// and their formats.</param>
        /// <param name="password">Password to join the meeting. Password may
        /// only contain the following characters: [a-z A-Z 0-9 @ - _ *]. Max
        /// of 10 characters.</param>
        /// <param name="agenda">Meeting description</param>
        /// <param name="trackingFields">Tracking fields</param>
        public Meeting(string topic = default(string), int? type = default(int?), System.DateTime? startTime = default(System.DateTime?), int? duration = default(int?), string timezone = default(string), string password = default(string), string agenda = default(string), IList<SessionTrackingFieldsItem> trackingFields = default(IList<SessionTrackingFieldsItem>), Recurrence recurrence = default(Recurrence), MeetingSettings settings = default(MeetingSettings))
            : base(topic, type, startTime, duration, timezone, password, agenda, trackingFields, recurrence, settings)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
