// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MeetingInfoTrackingFieldsItem
    {
        /// <summary>
        /// Initializes a new instance of the MeetingInfoTrackingFieldsItem
        /// class.
        /// </summary>
        public MeetingInfoTrackingFieldsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MeetingInfoTrackingFieldsItem
        /// class.
        /// </summary>
        /// <param name="field">Tracking fields type</param>
        /// <param name="value">Tracking fields value</param>
        public MeetingInfoTrackingFieldsItem(string field = default(string), string value = default(string))
        {
            Field = field;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets tracking fields type
        /// </summary>
        [JsonProperty(PropertyName = "field")]
        public string Field { get; set; }

        /// <summary>
        /// Gets or sets tracking fields value
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
