// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MeetingInfoCreated : MeetingInfo
    {
        /// <summary>
        /// Initializes a new instance of the MeetingInfoCreated class.
        /// </summary>
        public MeetingInfoCreated()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MeetingInfoCreated class.
        /// </summary>
        /// <param name="topic">Meeting topic</param>
        /// <param name="type">Meeting Type</param>
        /// <param name="startTime">Meeting start time</param>
        /// <param name="duration">Meeting duration</param>
        /// <param name="timezone">Timezone to format start_time</param>
        /// <param name="createdAt">Create time</param>
        /// <param name="agenda">Agenda</param>
        /// <param name="startUrl">Start url</param>
        /// <param name="joinUrl">Join url</param>
        /// <param name="password">Meeting password</param>
        /// <param name="h323Password">H.323/SIP room system password</param>
        /// <param name="trackingFields">Tracking fields</param>
        /// <param name="uuid">Meeting unique ID</param>
        /// <param name="id">Meeting ID, also known as meeting number</param>
        /// <param name="hostId">ID of the user set as host of meeting</param>
        public MeetingInfoCreated(string topic = default(string), int? type = default(int?), System.DateTime? startTime = default(System.DateTime?), int? duration = default(int?), string timezone = default(string), System.DateTime? createdAt = default(System.DateTime?), string agenda = default(string), string startUrl = default(string), string joinUrl = default(string), string password = default(string), string h323Password = default(string), IList<MeetingInfoTrackingFieldsItem> trackingFields = default(IList<MeetingInfoTrackingFieldsItem>), IList<Occurrence> occurrences = default(IList<Occurrence>), MeetingSettings settings = default(MeetingSettings), string uuid = default(string), string id = default(string), string hostId = default(string))
            : base(topic, type, startTime, duration, timezone, createdAt, agenda, startUrl, joinUrl, password, h323Password, trackingFields, occurrences, settings)
        {
            Uuid = uuid;
            Id = id;
            HostId = hostId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets meeting unique ID
        /// </summary>
        [JsonProperty(PropertyName = "uuid")]
        public string Uuid { get; set; }

        /// <summary>
        /// Gets or sets meeting ID, also known as meeting number
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets ID of the user set as host of meeting
        /// </summary>
        [JsonProperty(PropertyName = "host_id")]
        public string HostId { get; set; }

    }
}
