// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Group List
    /// </summary>
    /// <remarks>
    /// List of Meetings
    /// </remarks>
    public partial class MeetingList : Pagination
    {
        /// <summary>
        /// Initializes a new instance of the MeetingList class.
        /// </summary>
        public MeetingList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MeetingList class.
        /// </summary>
        /// <param name="pageCount">The number of items returned on this
        /// page</param>
        /// <param name="pageNumber">The page number of current results</param>
        /// <param name="pageSize">The number of records returned within a
        /// single API call</param>
        /// <param name="totalRecords">The number of all records available
        /// across pages</param>
        /// <param name="meetings">List of Meeting objects</param>
        public MeetingList(int? pageCount = default(int?), int? pageNumber = default(int?), int? pageSize = default(int?), int? totalRecords = default(int?), IList<MeetingListMeetingsItem> meetings = default(IList<MeetingListMeetingsItem>))
            : base(pageCount, pageNumber, pageSize, totalRecords)
        {
            Meetings = meetings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of Meeting objects
        /// </summary>
        [JsonProperty(PropertyName = "meetings")]
        public IList<MeetingListMeetingsItem> Meetings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
