// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Meeting Settings
    /// </summary>
    public partial class MeetingSettings
    {
        /// <summary>
        /// Initializes a new instance of the MeetingSettings class.
        /// </summary>
        public MeetingSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MeetingSettings class.
        /// </summary>
        /// <param name="hostVideo">Start video when host joins meeting</param>
        /// <param name="participantVideo">Start video when participants join
        /// meeting</param>
        /// <param name="cnMeeting">Host meeting in China</param>
        /// <param name="inMeeting">Host meeting in India</param>
        /// <param name="joinBeforeHost">Allow participants to join the meeting
        /// before the host starts the meeting. Only used for scheduled or
        /// recurring meetings.</param>
        /// <param name="muteUponEntry">Mute participants upon entry</param>
        /// <param name="watermark">Add watermark when viewing shared
        /// screen</param>
        /// <param name="usePmi">Use Personal Meeting ID. Only used for
        /// scheduled meetings and recurring meetings with no fixed
        /// time.</param>
        /// <param name="registrationType">Registration type. Used for
        /// recurring meeting with fixed time only.</param>
        /// <param name="audio">Determine how participants can join the audio
        /// portion of the meeting. Possible values include: 'both',
        /// 'telephony', 'voip'</param>
        /// <param name="autoRecording">Possible values include: 'local',
        /// 'cloud', 'none'</param>
        /// <param name="enforceLogin">Only signed-in users can join this
        /// meeting</param>
        /// <param name="enforceLoginDomains">Only signed-in users with
        /// specified domains can join meetings</param>
        /// <param name="alternativeHosts">Alternative hosts emails or IDs.
        /// Multiple value separated by comma.</param>
        /// <param name="closeRegistration">Close registration after event
        /// date</param>
        /// <param name="waitingRoom">Enable waiting room</param>
        public MeetingSettings(bool? hostVideo = default(bool?), bool? participantVideo = default(bool?), bool? cnMeeting = default(bool?), bool? inMeeting = default(bool?), bool? joinBeforeHost = default(bool?), bool? muteUponEntry = default(bool?), bool? watermark = default(bool?), bool? usePmi = default(bool?), int? approvalType = default(int?), int? registrationType = default(int?), string audio = default(string), string autoRecording = default(string), bool? enforceLogin = default(bool?), string enforceLoginDomains = default(string), string alternativeHosts = default(string), bool? closeRegistration = default(bool?), bool? waitingRoom = default(bool?))
        {
            HostVideo = hostVideo;
            ParticipantVideo = participantVideo;
            CnMeeting = cnMeeting;
            InMeeting = inMeeting;
            JoinBeforeHost = joinBeforeHost;
            MuteUponEntry = muteUponEntry;
            Watermark = watermark;
            UsePmi = usePmi;
            ApprovalType = approvalType;
            RegistrationType = registrationType;
            Audio = audio;
            AutoRecording = autoRecording;
            EnforceLogin = enforceLogin;
            EnforceLoginDomains = enforceLoginDomains;
            AlternativeHosts = alternativeHosts;
            CloseRegistration = closeRegistration;
            WaitingRoom = waitingRoom;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets start video when host joins meeting
        /// </summary>
        [JsonProperty(PropertyName = "host_video")]
        public bool? HostVideo { get; set; }

        /// <summary>
        /// Gets or sets start video when participants join meeting
        /// </summary>
        [JsonProperty(PropertyName = "participant_video")]
        public bool? ParticipantVideo { get; set; }

        /// <summary>
        /// Gets or sets host meeting in China
        /// </summary>
        [JsonProperty(PropertyName = "cn_meeting")]
        public bool? CnMeeting { get; set; }

        /// <summary>
        /// Gets or sets host meeting in India
        /// </summary>
        [JsonProperty(PropertyName = "in_meeting")]
        public bool? InMeeting { get; set; }

        /// <summary>
        /// Gets or sets allow participants to join the meeting before the host
        /// starts the meeting. Only used for scheduled or recurring meetings.
        /// </summary>
        [JsonProperty(PropertyName = "join_before_host")]
        public bool? JoinBeforeHost { get; set; }

        /// <summary>
        /// Gets or sets mute participants upon entry
        /// </summary>
        [JsonProperty(PropertyName = "mute_upon_entry")]
        public bool? MuteUponEntry { get; set; }

        /// <summary>
        /// Gets or sets add watermark when viewing shared screen
        /// </summary>
        [JsonProperty(PropertyName = "watermark")]
        public bool? Watermark { get; set; }

        /// <summary>
        /// Gets or sets use Personal Meeting ID. Only used for scheduled
        /// meetings and recurring meetings with no fixed time.
        /// </summary>
        [JsonProperty(PropertyName = "use_pmi")]
        public bool? UsePmi { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "approval_type")]
        public int? ApprovalType { get; set; }

        /// <summary>
        /// Gets or sets registration type. Used for recurring meeting with
        /// fixed time only.
        /// </summary>
        [JsonProperty(PropertyName = "registration_type")]
        public int? RegistrationType { get; set; }

        /// <summary>
        /// Gets or sets determine how participants can join the audio portion
        /// of the meeting. Possible values include: 'both', 'telephony',
        /// 'voip'
        /// </summary>
        [JsonProperty(PropertyName = "audio")]
        public string Audio { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'local', 'cloud', 'none'
        /// </summary>
        [JsonProperty(PropertyName = "auto_recording")]
        public string AutoRecording { get; set; }

        /// <summary>
        /// Gets or sets only signed-in users can join this meeting
        /// </summary>
        [JsonProperty(PropertyName = "enforce_login")]
        public bool? EnforceLogin { get; set; }

        /// <summary>
        /// Gets or sets only signed-in users with specified domains can join
        /// meetings
        /// </summary>
        [JsonProperty(PropertyName = "enforce_login_domains")]
        public string EnforceLoginDomains { get; set; }

        /// <summary>
        /// Gets or sets alternative hosts emails or IDs. Multiple value
        /// separated by comma.
        /// </summary>
        [JsonProperty(PropertyName = "alternative_hosts")]
        public string AlternativeHosts { get; set; }

        /// <summary>
        /// Gets or sets close registration after event date
        /// </summary>
        [JsonProperty(PropertyName = "close_registration")]
        public bool? CloseRegistration { get; set; }

        /// <summary>
        /// Gets or sets enable waiting room
        /// </summary>
        [JsonProperty(PropertyName = "waiting_room")]
        public bool? WaitingRoom { get; set; }

    }
}
