// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for meetingCreate operation.
    /// </summary>
    public partial class MeetingCreateHeaders
    {
        /// <summary>
        /// Initializes a new instance of the MeetingCreateHeaders class.
        /// </summary>
        public MeetingCreateHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MeetingCreateHeaders class.
        /// </summary>
        /// <param name="contentLocation">Location of created Meeting</param>
        public MeetingCreateHeaders(string contentLocation = default(string))
        {
            ContentLocation = contentLocation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets location of created Meeting
        /// </summary>
        [JsonProperty(PropertyName = "Content-Location")]
        public string ContentLocation { get; set; }

    }
}
