// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Meeting object
    /// </summary>
    public partial class MeetingInfo
    {
        /// <summary>
        /// Initializes a new instance of the MeetingInfo class.
        /// </summary>
        public MeetingInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MeetingInfo class.
        /// </summary>
        /// <param name="topic">Meeting topic</param>
        /// <param name="type">Meeting Type</param>
        /// <param name="startTime">Meeting start time</param>
        /// <param name="duration">Meeting duration</param>
        /// <param name="timezone">Timezone to format start_time</param>
        /// <param name="createdAt">Create time</param>
        /// <param name="agenda">Agenda</param>
        /// <param name="startUrl">Start url</param>
        /// <param name="joinUrl">Join url</param>
        /// <param name="password">Meeting password</param>
        /// <param name="h323Password">H.323/SIP room system password</param>
        /// <param name="trackingFields">Tracking fields</param>
        public MeetingInfo(string topic = default(string), int? type = default(int?), System.DateTime? startTime = default(System.DateTime?), int? duration = default(int?), string timezone = default(string), System.DateTime? createdAt = default(System.DateTime?), string agenda = default(string), string startUrl = default(string), string joinUrl = default(string), string password = default(string), string h323Password = default(string), IList<MeetingInfoTrackingFieldsItem> trackingFields = default(IList<MeetingInfoTrackingFieldsItem>), IList<Occurrence> occurrences = default(IList<Occurrence>), MeetingSettings settings = default(MeetingSettings))
        {
            Topic = topic;
            Type = type;
            StartTime = startTime;
            Duration = duration;
            Timezone = timezone;
            CreatedAt = createdAt;
            Agenda = agenda;
            StartUrl = startUrl;
            JoinUrl = joinUrl;
            Password = password;
            H323Password = h323Password;
            TrackingFields = trackingFields;
            Occurrences = occurrences;
            Settings = settings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets meeting topic
        /// </summary>
        [JsonProperty(PropertyName = "topic")]
        public string Topic { get; set; }

        /// <summary>
        /// Gets or sets meeting Type
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// Gets or sets meeting start time
        /// </summary>
        [JsonProperty(PropertyName = "start_time")]
        public System.DateTime? StartTime { get; set; }

        /// <summary>
        /// Gets or sets meeting duration
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public int? Duration { get; set; }

        /// <summary>
        /// Gets or sets timezone to format start_time
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public string Timezone { get; set; }

        /// <summary>
        /// Gets or sets create time
        /// </summary>
        [JsonProperty(PropertyName = "created_at")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets agenda
        /// </summary>
        [JsonProperty(PropertyName = "agenda")]
        public string Agenda { get; set; }

        /// <summary>
        /// Gets or sets start url
        /// </summary>
        [JsonProperty(PropertyName = "start_url")]
        public string StartUrl { get; set; }

        /// <summary>
        /// Gets or sets join url
        /// </summary>
        [JsonProperty(PropertyName = "join_url")]
        public string JoinUrl { get; set; }

        /// <summary>
        /// Gets or sets meeting password
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// Gets or sets H.323/SIP room system password
        /// </summary>
        [JsonProperty(PropertyName = "h323_password")]
        public string H323Password { get; set; }

        /// <summary>
        /// Gets or sets tracking fields
        /// </summary>
        [JsonProperty(PropertyName = "tracking_fields")]
        public IList<MeetingInfoTrackingFieldsItem> TrackingFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "occurrences")]
        public IList<Occurrence> Occurrences { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "settings")]
        public MeetingSettings Settings { get; set; }

    }
}
