// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Pagination Object
    /// </summary>
    public partial class PaginationToken
    {
        /// <summary>
        /// Initializes a new instance of the PaginationToken class.
        /// </summary>
        public PaginationToken()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaginationToken class.
        /// </summary>
        /// <param name="pageCount">The number of items returned on this
        /// page</param>
        /// <param name="pageSize">The number of records returned within a
        /// single API call.</param>
        /// <param name="totalRecords">The number of all records available
        /// across pages</param>
        /// <param name="nextPageToken">Next page token is used to paginate
        /// through large result sets. A next page token will be returned
        /// whenever the set of available results exceed the current page size.
        /// The expiration period for this token is 15 minutes.</param>
        public PaginationToken(int? pageCount = default(int?), int? pageSize = default(int?), int? totalRecords = default(int?), string nextPageToken = default(string))
        {
            PageCount = pageCount;
            PageSize = pageSize;
            TotalRecords = totalRecords;
            NextPageToken = nextPageToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the number of items returned on this page
        /// </summary>
        [JsonProperty(PropertyName = "page_count")]
        public int? PageCount { get; set; }

        /// <summary>
        /// Gets or sets the number of records returned within a single API
        /// call.
        /// </summary>
        [JsonProperty(PropertyName = "page_size")]
        public int? PageSize { get; set; }

        /// <summary>
        /// Gets or sets the number of all records available across pages
        /// </summary>
        [JsonProperty(PropertyName = "total_records")]
        public int? TotalRecords { get; set; }

        /// <summary>
        /// Gets or sets next page token is used to paginate through large
        /// result sets. A next page token will be returned whenever the set of
        /// available results exceed the current page size. The expiration
        /// period for this token is 15 minutes.
        /// </summary>
        [JsonProperty(PropertyName = "next_page_token")]
        public string NextPageToken { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (PageSize > 300)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "PageSize", 300);
            }
        }
    }
}
