// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Recurrence object
    /// </summary>
    public partial class Recurrence
    {
        /// <summary>
        /// Initializes a new instance of the Recurrence class.
        /// </summary>
        public Recurrence()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Recurrence class.
        /// </summary>
        /// <param name="type">Recurrence meeting type</param>
        /// <param name="repeatInterval">At which interval should the meeting
        /// repeat? For a daily meeting, max of 90 days. For a weekly meeting,
        /// max of 12 weeks. For a monthly meeting, max of 3 months.</param>
        /// <param name="weeklyDays">Days of the week the meeting should
        /// repeat, multiple values separated by comma</param>
        /// <param name="monthlyDay">Day of the month for the meeting to be
        /// scheduled. The value range is from 1 to 31.</param>
        /// <param name="monthlyWeek">Week for which the meeting should recur
        /// each month,</param>
        /// <param name="monthlyWeekDay">Day for which the meeting should recur
        /// each month</param>
        /// <param name="endTimes">Select how many times the meeting will occur
        /// before it is canceled. (Cannot be used with
        /// "end_date_time".)</param>
        /// <param name="endDateTime">Select a date the meeting will occur
        /// before it is canceled.. Should be UTC time, such as
        /// 2017-11-25T12:00:00Z. (Cannot be used with "end_times".)</param>
        public Recurrence(int? type = default(int?), int? repeatInterval = default(int?), int? weeklyDays = default(int?), int? monthlyDay = default(int?), int? monthlyWeek = default(int?), int? monthlyWeekDay = default(int?), int? endTimes = default(int?), System.DateTime? endDateTime = default(System.DateTime?))
        {
            Type = type;
            RepeatInterval = repeatInterval;
            WeeklyDays = weeklyDays;
            MonthlyDay = monthlyDay;
            MonthlyWeek = monthlyWeek;
            MonthlyWeekDay = monthlyWeekDay;
            EndTimes = endTimes;
            EndDateTime = endDateTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets recurrence meeting type
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// Gets or sets at which interval should the meeting repeat? For a
        /// daily meeting, max of 90 days. For a weekly meeting, max of 12
        /// weeks. For a monthly meeting, max of 3 months.
        /// </summary>
        [JsonProperty(PropertyName = "repeat_interval")]
        public int? RepeatInterval { get; set; }

        /// <summary>
        /// Gets or sets days of the week the meeting should repeat, multiple
        /// values separated by comma
        /// </summary>
        [JsonProperty(PropertyName = "weekly_days")]
        public int? WeeklyDays { get; set; }

        /// <summary>
        /// Gets or sets day of the month for the meeting to be scheduled. The
        /// value range is from 1 to 31.
        /// </summary>
        [JsonProperty(PropertyName = "monthly_day")]
        public int? MonthlyDay { get; set; }

        /// <summary>
        /// Gets or sets week for which the meeting should recur each month,
        /// </summary>
        [JsonProperty(PropertyName = "monthly_week")]
        public int? MonthlyWeek { get; set; }

        /// <summary>
        /// Gets or sets day for which the meeting should recur each month
        /// </summary>
        [JsonProperty(PropertyName = "monthly_week_day")]
        public int? MonthlyWeekDay { get; set; }

        /// <summary>
        /// Gets or sets select how many times the meeting will occur before it
        /// is canceled. (Cannot be used with "end_date_time".)
        /// </summary>
        [JsonProperty(PropertyName = "end_times")]
        public int? EndTimes { get; set; }

        /// <summary>
        /// Gets or sets select a date the meeting will occur before it is
        /// canceled.. Should be UTC time, such as 2017-11-25T12:00:00Z.
        /// (Cannot be used with "end_times".)
        /// </summary>
        [JsonProperty(PropertyName = "end_date_time")]
        public System.DateTime? EndDateTime { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (EndTimes > 50)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "EndTimes", 50);
            }
        }
    }
}
