// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PI.Zoom.API.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Base object for sessions
    /// </summary>
    public partial class Session
    {
        /// <summary>
        /// Initializes a new instance of the Session class.
        /// </summary>
        public Session()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Session class.
        /// </summary>
        /// <param name="topic">Meeting topic</param>
        /// <param name="type">Meeting Type</param>
        /// <param name="startTime">Meeting start time. When using a format
        /// like "yyyy-MM-dd'T'HH:mm:ss'Z'", always use GMT time. When using a
        /// format like "yyyy-MM-dd'T'HH:mm:ss", you should use local time and
        /// you will need to specify the time zone. Only used for scheduled
        /// meetings and recurring meetings with fixed time.</param>
        /// <param name="duration">Meeting duration (minutes). Used for
        /// scheduled meetings only</param>
        /// <param name="timezone">Timezone to format start_time. For example,
        /// "America/Los_Angeles". For scheduled meetings only. Please
        /// reference our [timezone](#timezones) list for supported timezones
        /// and their formats.</param>
        /// <param name="password">Password to join the meeting. Password may
        /// only contain the following characters: [a-z A-Z 0-9 @ - _ *]. Max
        /// of 10 characters.</param>
        /// <param name="agenda">Meeting description</param>
        /// <param name="trackingFields">Tracking fields</param>
        public Session(string topic = default(string), int? type = default(int?), System.DateTime? startTime = default(System.DateTime?), int? duration = default(int?), string timezone = default(string), string password = default(string), string agenda = default(string), IList<SessionTrackingFieldsItem> trackingFields = default(IList<SessionTrackingFieldsItem>), Recurrence recurrence = default(Recurrence), MeetingSettings settings = default(MeetingSettings))
        {
            Topic = topic;
            Type = type;
            StartTime = startTime;
            Duration = duration;
            Timezone = timezone;
            Password = password;
            Agenda = agenda;
            TrackingFields = trackingFields;
            Recurrence = recurrence;
            Settings = settings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets meeting topic
        /// </summary>
        [JsonProperty(PropertyName = "topic")]
        public string Topic { get; set; }

        /// <summary>
        /// Gets or sets meeting Type
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// Gets or sets meeting start time. When using a format like
        /// "yyyy-MM-dd'T'HH:mm:ss'Z'", always use GMT time. When using a
        /// format like "yyyy-MM-dd'T'HH:mm:ss", you should use local time and
        /// you will need to specify the time zone. Only used for scheduled
        /// meetings and recurring meetings with fixed time.
        /// </summary>
        [JsonProperty(PropertyName = "start_time")]
        public System.DateTime? StartTime { get; set; }

        /// <summary>
        /// Gets or sets meeting duration (minutes). Used for scheduled
        /// meetings only
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public int? Duration { get; set; }

        /// <summary>
        /// Gets or sets timezone to format start_time. For example,
        /// "America/Los_Angeles". For scheduled meetings only. Please
        /// reference our [timezone](#timezones) list for supported timezones
        /// and their formats.
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public string Timezone { get; set; }

        /// <summary>
        /// Gets or sets password to join the meeting. Password may only
        /// contain the following characters: [a-z A-Z 0-9 @ - _ *]. Max of 10
        /// characters.
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// Gets or sets meeting description
        /// </summary>
        [JsonProperty(PropertyName = "agenda")]
        public string Agenda { get; set; }

        /// <summary>
        /// Gets or sets tracking fields
        /// </summary>
        [JsonProperty(PropertyName = "tracking_fields")]
        public IList<SessionTrackingFieldsItem> TrackingFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recurrence")]
        public Recurrence Recurrence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "settings")]
        public MeetingSettings Settings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Recurrence != null)
            {
                Recurrence.Validate();
            }
        }
    }
}
