using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Messages.Flow;
using PI.Shared.Constants;
using PI.Shared.Exceptions;
using PI.Shared.Extensions;
using PI.Shared.Form.Models;
using PI.Shared.Models;
using PI.Shared.Services;

namespace FlowActions;

public abstract class AbstractGenericActionBuilder : IFlowActionBuilder
{
    private const string ObjectStatusIdFieldName = "stepObjectStatusId";
    private const string DescriptionFieldName = "stepDescription";
    private readonly ObjectTypeService _objectTypeService;
    
    public abstract Guid Id { get; }
    public abstract string Name { get; }
    public abstract string IconName { get; }
    public abstract string Description { get; }
    public abstract string[] InputObjectTypes { get; }
    
    protected abstract string ActionOptionsObjectType { get; }
    
    public abstract bool IsValidTrigger(string objectType);
    // public abstract Task<FlowStep> AddOrUpdateStepAsync(IEntityContext context, Flow flow, Guid eventTypeId, Dictionary<string, object> requestParameters, FlowStep flowStep = null);
    public abstract ValueTask SwapAsync(IEntityContext context, FlowStep step, Dictionary<Guid, Guid?> swap);
    
    public ValueTask<IEnumerable<Placeholder>> GetPlaceholdersForOutputAsync(IEntityContext context, Flow flow, ActionOptions triggerOptions, IEnumerable<Placeholder> placeholders, Guid stepEventIdTrigger)
    {
        // remove generated from previous event
        var list = placeholders.Where(x=>!x.Name.StartsWith("{{Event."));
        
        // TODO: add generated by action
        // ...

        return ValueTask.FromResult(list);
    }

    protected abstract GenericActionOptions CalculateGenericOptions(ExpandoObject raw, GenericActionOptions current = null);
    
    public virtual (IActionMessage Message, string Route) Build<T>(IEntityContext context, T evt, IActionOptions options) where T : FlowEvent
    {
        if (options is not GenericActionOptions genericActionOptions)
        {
            throw new BadRequestException("Invalid Options");
        }
        
        var message = new SimpleActionMessage<GenericActionOptions>(evt, genericActionOptions);
        var route = ActionIds.GetRoute(Id);
        
        return (message, route);
    }
    
    protected AbstractGenericActionBuilder(ObjectTypeService objectTypeService)
    {
        _objectTypeService = objectTypeService;
    }
    
    // public abstract Task<Form> GetFormAsync(FlowActionContext flowActionContext, Guid? objectStatusId, FlowStep step = null);
    
    public virtual async Task<Form> GetFormAsync(FlowActionContext flowActionContext, Guid? objectStatusId, FlowStep step = null)
    {
        var actionOptionObjectType = await _objectTypeService.GetAsync(flowActionContext.EntityContext, ActionOptionsObjectType);
        if (actionOptionObjectType == null) throw NotFoundException.New(ActionOptionsObjectType);

        if (step == null)
        {
            var addForm = await _objectTypeService.GetAddDataFormAsync(flowActionContext.EntityContext, actionOptionObjectType);

            // object status field
            addForm.Fields = (addForm.Fields ?? Enumerable.Empty<FormField>())
                .Append(
                    new HiddenField
                    {
                        Name = ObjectStatusIdFieldName,
                        DefaultValue = objectStatusId,
                    }
                )
                .ToArray();

            // no menu, for now
            addForm.Menu = null;

            return addForm;
        }

        if (step.Options is not GenericActionOptions options || options.Raw == null)
        {
            throw new BadRequestException("Invalid options");
        }

        var editForm = await _objectTypeService.GetEditDataFormAsync(flowActionContext.EntityContext, actionOptionObjectType, null, options.Raw);
        editForm.Fields = (editForm.Fields ?? Enumerable.Empty<FormField>())
            .Prepend(new TextField
            {
                Name = DescriptionFieldName,
                Label = "Step Description",
                DefaultValue = step.Description,
            })
            .ToArray();
        
        // no menu, for now
        editForm.Menu = null;
        
        return editForm;
    }    
    
    public virtual async Task<FlowStep> AddOrUpdateStepAsync(IEntityContext context, Flow flow, Guid eventTypeId, Dictionary<string, object> requestParameters, FlowStep flowStep = null)
    {
        var actionOptionObjectType = await _objectTypeService.GetAsync(context, ActionOptionsObjectType);
        if (actionOptionObjectType == null) throw NotFoundException.New(ActionOptionsObjectType);

        var optionsResult = await _objectTypeService.GetFieldValuesFromUserInputAsync(context, actionOptionObjectType, new ObjectTypeService.GetValuesFromInputOptions
            {
                Input = requestParameters,
            }
        );
        
        if (!optionsResult)
        {
            throw new BadRequestException(optionsResult.Status);
        }

        var objectStatusId = default(Guid?);
        if (requestParameters.TryGetGuidParam(ObjectStatusIdFieldName, out var selObjectStatusId) && selObjectStatusId != Guid.Empty)
        {
            objectStatusId = selObjectStatusId;
        }

        var rawActionOptions = GenericActionOptions.Convert<IDictionary<string, object>, ExpandoObject>(optionsResult.Value);
        var genericActionOptions = CalculateGenericOptions(rawActionOptions, flowStep?.Options as GenericActionOptions);
        
        if (flowStep == null)
        {
            return new FlowStep
            {
                Id = Guid.NewGuid(),
                EventIdTrigger = eventTypeId,
                CurrentStatusId = objectStatusId,
                Description = Description,
                IconName = IconName,
                ActionId = Id,
                Options = genericActionOptions,
            };
        }

        flowStep.Options = genericActionOptions;
        
        // update step description
        if (requestParameters.TryGetStrParam(DescriptionFieldName, out var stepDescription))
        {
            flowStep.Description = stepDescription;
        }

        return flowStep;
    }
}