/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes an attendee of a meeting instance held by an organizer within a specified group.
    /// </summary>
    [DataContract]
    public partial class AttendeeByGroup :  IEquatable<AttendeeByGroup>
    {
        /// <summary>
        /// The meeting type
        /// </summary>
        /// <value>The meeting type</value>
        [DataMember(Name="meetingType", EmitDefaultValue=false)]
        public MeetingType MeetingType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AttendeeByGroup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AttendeeByGroup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AttendeeByGroup" /> class.
        /// </summary>
        /// <param name="lastName">The surname of the meeting organizer (required).</param>
        /// <param name="groupName">The name of the group (required).</param>
        /// <param name="numAttendees">The number of attendees at the attended meeting instance (required).</param>
        /// <param name="attendeeName">The full name of the attendee (required).</param>
        /// <param name="subject">The subject of the attended meeting (required).</param>
        /// <param name="endTime">The time the meeting instance ended (required).</param>
        /// <param name="conferenceCallInfo">Audio options for the attended meeting (required).</param>
        /// <param name="organizerkey">The key of the meeting organizer. Field retained for backwards compatibility reasons (required).</param>
        /// <param name="startTime">The time the meeting instance started (required).</param>
        /// <param name="meetingInstanceKey">The key of the attended meeting instance (required).</param>
        /// <param name="duration">The duration of attendance in minutes (required).</param>
        /// <param name="joinTime">The time the attendee joined the meeting instance (required).</param>
        /// <param name="email">The email address of the meeting organizer (required).</param>
        /// <param name="leaveTime">The time the attendee left the meeting instance (required).</param>
        /// <param name="attendeeEmail">The attendee&#39;s email address (required).</param>
        /// <param name="organizerKey">The key of the meeting organizer (required).</param>
        /// <param name="meetingId">The meeting ID (required).</param>
        /// <param name="meetingType">The meeting type (required).</param>
        /// <param name="firstName">The first name of the organizer of the attended meeting (required).</param>
        public AttendeeByGroup(string lastName = default(string), string groupName = default(string), int? numAttendees = default(int?), string attendeeName = default(string), string subject = default(string), DateTime? endTime = default(DateTime?), string conferenceCallInfo = default(string), long? organizerkey = default(long?), DateTime? startTime = default(DateTime?), long? meetingInstanceKey = default(long?), int? duration = default(int?), DateTime? joinTime = default(DateTime?), string email = default(string), DateTime? leaveTime = default(DateTime?), string attendeeEmail = default(string), string organizerKey = default(string), string meetingId = default(string), MeetingType meetingType = default(MeetingType), string firstName = default(string))
        {
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new InvalidDataException("lastName is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.LastName = lastName;
            }
            // to ensure "groupName" is required (not null)
            if (groupName == null)
            {
                throw new InvalidDataException("groupName is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.GroupName = groupName;
            }
            // to ensure "numAttendees" is required (not null)
            if (numAttendees == null)
            {
                throw new InvalidDataException("numAttendees is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.NumAttendees = numAttendees;
            }
            // to ensure "attendeeName" is required (not null)
            if (attendeeName == null)
            {
                throw new InvalidDataException("attendeeName is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.AttendeeName = attendeeName;
            }
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new InvalidDataException("subject is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.Subject = subject;
            }
            // to ensure "endTime" is required (not null)
            if (endTime == null)
            {
                throw new InvalidDataException("endTime is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.EndTime = endTime;
            }
            // to ensure "conferenceCallInfo" is required (not null)
            if (conferenceCallInfo == null)
            {
                throw new InvalidDataException("conferenceCallInfo is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.ConferenceCallInfo = conferenceCallInfo;
            }
            // to ensure "organizerkey" is required (not null)
            if (organizerkey == null)
            {
                throw new InvalidDataException("organizerkey is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.Organizerkey = organizerkey;
            }
            // to ensure "startTime" is required (not null)
            if (startTime == null)
            {
                throw new InvalidDataException("startTime is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.StartTime = startTime;
            }
            // to ensure "meetingInstanceKey" is required (not null)
            if (meetingInstanceKey == null)
            {
                throw new InvalidDataException("meetingInstanceKey is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.MeetingInstanceKey = meetingInstanceKey;
            }
            // to ensure "duration" is required (not null)
            if (duration == null)
            {
                throw new InvalidDataException("duration is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.Duration = duration;
            }
            // to ensure "joinTime" is required (not null)
            if (joinTime == null)
            {
                throw new InvalidDataException("joinTime is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.JoinTime = joinTime;
            }
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "leaveTime" is required (not null)
            if (leaveTime == null)
            {
                throw new InvalidDataException("leaveTime is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.LeaveTime = leaveTime;
            }
            // to ensure "attendeeEmail" is required (not null)
            if (attendeeEmail == null)
            {
                throw new InvalidDataException("attendeeEmail is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.AttendeeEmail = attendeeEmail;
            }
            // to ensure "organizerKey" is required (not null)
            if (organizerKey == null)
            {
                throw new InvalidDataException("organizerKey is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.OrganizerKey = organizerKey;
            }
            // to ensure "meetingId" is required (not null)
            if (meetingId == null)
            {
                throw new InvalidDataException("meetingId is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.MeetingId = meetingId;
            }
            // to ensure "meetingType" is required (not null)
            if (meetingType == null)
            {
                throw new InvalidDataException("meetingType is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.MeetingType = meetingType;
            }
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new InvalidDataException("firstName is a required property for AttendeeByGroup and cannot be null");
            }
            else
            {
                this.FirstName = firstName;
            }
        }
        
        /// <summary>
        /// The surname of the meeting organizer
        /// </summary>
        /// <value>The surname of the meeting organizer</value>
        [DataMember(Name="lastName", EmitDefaultValue=false)]
        public string LastName { get; set; }

        /// <summary>
        /// The name of the group
        /// </summary>
        /// <value>The name of the group</value>
        [DataMember(Name="groupName", EmitDefaultValue=false)]
        public string GroupName { get; set; }

        /// <summary>
        /// The number of attendees at the attended meeting instance
        /// </summary>
        /// <value>The number of attendees at the attended meeting instance</value>
        [DataMember(Name="numAttendees", EmitDefaultValue=false)]
        public int? NumAttendees { get; set; }

        /// <summary>
        /// The full name of the attendee
        /// </summary>
        /// <value>The full name of the attendee</value>
        [DataMember(Name="attendeeName", EmitDefaultValue=false)]
        public string AttendeeName { get; set; }

        /// <summary>
        /// The subject of the attended meeting
        /// </summary>
        /// <value>The subject of the attended meeting</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// The time the meeting instance ended
        /// </summary>
        /// <value>The time the meeting instance ended</value>
        [DataMember(Name="endTime", EmitDefaultValue=false)]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// Audio options for the attended meeting
        /// </summary>
        /// <value>Audio options for the attended meeting</value>
        [DataMember(Name="conferenceCallInfo", EmitDefaultValue=false)]
        public string ConferenceCallInfo { get; set; }

        /// <summary>
        /// The key of the meeting organizer. Field retained for backwards compatibility reasons
        /// </summary>
        /// <value>The key of the meeting organizer. Field retained for backwards compatibility reasons</value>
        [DataMember(Name="organizerkey", EmitDefaultValue=false)]
        public long? Organizerkey { get; set; }

        /// <summary>
        /// The time the meeting instance started
        /// </summary>
        /// <value>The time the meeting instance started</value>
        [DataMember(Name="startTime", EmitDefaultValue=false)]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// The key of the attended meeting instance
        /// </summary>
        /// <value>The key of the attended meeting instance</value>
        [DataMember(Name="meetingInstanceKey", EmitDefaultValue=false)]
        public long? MeetingInstanceKey { get; set; }

        /// <summary>
        /// The duration of attendance in minutes
        /// </summary>
        /// <value>The duration of attendance in minutes</value>
        [DataMember(Name="duration", EmitDefaultValue=false)]
        public int? Duration { get; set; }

        /// <summary>
        /// The time the attendee joined the meeting instance
        /// </summary>
        /// <value>The time the attendee joined the meeting instance</value>
        [DataMember(Name="joinTime", EmitDefaultValue=false)]
        public DateTime? JoinTime { get; set; }

        /// <summary>
        /// The email address of the meeting organizer
        /// </summary>
        /// <value>The email address of the meeting organizer</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// The time the attendee left the meeting instance
        /// </summary>
        /// <value>The time the attendee left the meeting instance</value>
        [DataMember(Name="leaveTime", EmitDefaultValue=false)]
        public DateTime? LeaveTime { get; set; }

        /// <summary>
        /// The attendee&#39;s email address
        /// </summary>
        /// <value>The attendee&#39;s email address</value>
        [DataMember(Name="attendeeEmail", EmitDefaultValue=false)]
        public string AttendeeEmail { get; set; }

        /// <summary>
        /// The key of the meeting organizer
        /// </summary>
        /// <value>The key of the meeting organizer</value>
        [DataMember(Name="organizerKey", EmitDefaultValue=false)]
        public string OrganizerKey { get; set; }

        /// <summary>
        /// The meeting ID
        /// </summary>
        /// <value>The meeting ID</value>
        [DataMember(Name="meetingId", EmitDefaultValue=false)]
        public string MeetingId { get; set; }


        /// <summary>
        /// The first name of the organizer of the attended meeting
        /// </summary>
        /// <value>The first name of the organizer of the attended meeting</value>
        [DataMember(Name="firstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AttendeeByGroup {\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("  NumAttendees: ").Append(NumAttendees).Append("\n");
            sb.Append("  AttendeeName: ").Append(AttendeeName).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  ConferenceCallInfo: ").Append(ConferenceCallInfo).Append("\n");
            sb.Append("  Organizerkey: ").Append(Organizerkey).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  MeetingInstanceKey: ").Append(MeetingInstanceKey).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  JoinTime: ").Append(JoinTime).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  LeaveTime: ").Append(LeaveTime).Append("\n");
            sb.Append("  AttendeeEmail: ").Append(AttendeeEmail).Append("\n");
            sb.Append("  OrganizerKey: ").Append(OrganizerKey).Append("\n");
            sb.Append("  MeetingId: ").Append(MeetingId).Append("\n");
            sb.Append("  MeetingType: ").Append(MeetingType).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AttendeeByGroup);
        }

        /// <summary>
        /// Returns true if AttendeeByGroup instances are equal
        /// </summary>
        /// <param name="input">Instance of AttendeeByGroup to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AttendeeByGroup input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.GroupName == input.GroupName ||
                    (this.GroupName != null &&
                    this.GroupName.Equals(input.GroupName))
                ) && 
                (
                    this.NumAttendees == input.NumAttendees ||
                    (this.NumAttendees != null &&
                    this.NumAttendees.Equals(input.NumAttendees))
                ) && 
                (
                    this.AttendeeName == input.AttendeeName ||
                    (this.AttendeeName != null &&
                    this.AttendeeName.Equals(input.AttendeeName))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.EndTime == input.EndTime ||
                    (this.EndTime != null &&
                    this.EndTime.Equals(input.EndTime))
                ) && 
                (
                    this.ConferenceCallInfo == input.ConferenceCallInfo ||
                    (this.ConferenceCallInfo != null &&
                    this.ConferenceCallInfo.Equals(input.ConferenceCallInfo))
                ) && 
                (
                    this.Organizerkey == input.Organizerkey ||
                    (this.Organizerkey != null &&
                    this.Organizerkey.Equals(input.Organizerkey))
                ) && 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.MeetingInstanceKey == input.MeetingInstanceKey ||
                    (this.MeetingInstanceKey != null &&
                    this.MeetingInstanceKey.Equals(input.MeetingInstanceKey))
                ) && 
                (
                    this.Duration == input.Duration ||
                    (this.Duration != null &&
                    this.Duration.Equals(input.Duration))
                ) && 
                (
                    this.JoinTime == input.JoinTime ||
                    (this.JoinTime != null &&
                    this.JoinTime.Equals(input.JoinTime))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.LeaveTime == input.LeaveTime ||
                    (this.LeaveTime != null &&
                    this.LeaveTime.Equals(input.LeaveTime))
                ) && 
                (
                    this.AttendeeEmail == input.AttendeeEmail ||
                    (this.AttendeeEmail != null &&
                    this.AttendeeEmail.Equals(input.AttendeeEmail))
                ) && 
                (
                    this.OrganizerKey == input.OrganizerKey ||
                    (this.OrganizerKey != null &&
                    this.OrganizerKey.Equals(input.OrganizerKey))
                ) && 
                (
                    this.MeetingId == input.MeetingId ||
                    (this.MeetingId != null &&
                    this.MeetingId.Equals(input.MeetingId))
                ) && 
                (
                    this.MeetingType == input.MeetingType ||
                    (this.MeetingType != null &&
                    this.MeetingType.Equals(input.MeetingType))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.GroupName != null)
                    hashCode = hashCode * 59 + this.GroupName.GetHashCode();
                if (this.NumAttendees != null)
                    hashCode = hashCode * 59 + this.NumAttendees.GetHashCode();
                if (this.AttendeeName != null)
                    hashCode = hashCode * 59 + this.AttendeeName.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.EndTime != null)
                    hashCode = hashCode * 59 + this.EndTime.GetHashCode();
                if (this.ConferenceCallInfo != null)
                    hashCode = hashCode * 59 + this.ConferenceCallInfo.GetHashCode();
                if (this.Organizerkey != null)
                    hashCode = hashCode * 59 + this.Organizerkey.GetHashCode();
                if (this.StartTime != null)
                    hashCode = hashCode * 59 + this.StartTime.GetHashCode();
                if (this.MeetingInstanceKey != null)
                    hashCode = hashCode * 59 + this.MeetingInstanceKey.GetHashCode();
                if (this.Duration != null)
                    hashCode = hashCode * 59 + this.Duration.GetHashCode();
                if (this.JoinTime != null)
                    hashCode = hashCode * 59 + this.JoinTime.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.LeaveTime != null)
                    hashCode = hashCode * 59 + this.LeaveTime.GetHashCode();
                if (this.AttendeeEmail != null)
                    hashCode = hashCode * 59 + this.AttendeeEmail.GetHashCode();
                if (this.OrganizerKey != null)
                    hashCode = hashCode * 59 + this.OrganizerKey.GetHashCode();
                if (this.MeetingId != null)
                    hashCode = hashCode * 59 + this.MeetingId.GetHashCode();
                if (this.MeetingType != null)
                    hashCode = hashCode * 59 + this.MeetingType.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                return hashCode;
            }
        }
    }

}
