/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes a collection of organizers categorized by department or job function, for example. Can be a subgroup of a larger group.
    /// </summary>
    [DataContract]
    public partial class Group :  IEquatable<Group>
    {
        /// <summary>
        /// The status of this group, i.e. whether the organizers assigned to it are able to host meetings
        /// </summary>
        /// <value>The status of this group, i.e. whether the organizers assigned to it are able to host meetings</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public Status Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Group" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Group() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Group" /> class.
        /// </summary>
        /// <param name="groupkey">The key of this group (required).</param>
        /// <param name="groupName">The name of this group (required).</param>
        /// <param name="parentKey">The key of the parent group this group belongs to. Identical with the groupkey if this group is not a subgroup (required).</param>
        /// <param name="status">The status of this group, i.e. whether the organizers assigned to it are able to host meetings (required).</param>
        /// <param name="numOrganizers">The number of organizers assigned to this group (required).</param>
        public Group(long? groupkey = default(long?), string groupName = default(string), long? parentKey = default(long?), Status status = default(Status), int? numOrganizers = default(int?))
        {
            // to ensure "groupkey" is required (not null)
            if (groupkey == null)
            {
                throw new InvalidDataException("groupkey is a required property for Group and cannot be null");
            }
            else
            {
                this.Groupkey = groupkey;
            }
            // to ensure "groupName" is required (not null)
            if (groupName == null)
            {
                throw new InvalidDataException("groupName is a required property for Group and cannot be null");
            }
            else
            {
                this.GroupName = groupName;
            }
            // to ensure "parentKey" is required (not null)
            if (parentKey == null)
            {
                throw new InvalidDataException("parentKey is a required property for Group and cannot be null");
            }
            else
            {
                this.ParentKey = parentKey;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for Group and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "numOrganizers" is required (not null)
            if (numOrganizers == null)
            {
                throw new InvalidDataException("numOrganizers is a required property for Group and cannot be null");
            }
            else
            {
                this.NumOrganizers = numOrganizers;
            }
        }
        
        /// <summary>
        /// The key of this group
        /// </summary>
        /// <value>The key of this group</value>
        [DataMember(Name="groupkey", EmitDefaultValue=false)]
        public long? Groupkey { get; set; }

        /// <summary>
        /// The name of this group
        /// </summary>
        /// <value>The name of this group</value>
        [DataMember(Name="groupName", EmitDefaultValue=false)]
        public string GroupName { get; set; }

        /// <summary>
        /// The key of the parent group this group belongs to. Identical with the groupkey if this group is not a subgroup
        /// </summary>
        /// <value>The key of the parent group this group belongs to. Identical with the groupkey if this group is not a subgroup</value>
        [DataMember(Name="parentKey", EmitDefaultValue=false)]
        public long? ParentKey { get; set; }


        /// <summary>
        /// The number of organizers assigned to this group
        /// </summary>
        /// <value>The number of organizers assigned to this group</value>
        [DataMember(Name="numOrganizers", EmitDefaultValue=false)]
        public int? NumOrganizers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Group {\n");
            sb.Append("  Groupkey: ").Append(Groupkey).Append("\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("  ParentKey: ").Append(ParentKey).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  NumOrganizers: ").Append(NumOrganizers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Group);
        }

        /// <summary>
        /// Returns true if Group instances are equal
        /// </summary>
        /// <param name="input">Instance of Group to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Group input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Groupkey == input.Groupkey ||
                    (this.Groupkey != null &&
                    this.Groupkey.Equals(input.Groupkey))
                ) && 
                (
                    this.GroupName == input.GroupName ||
                    (this.GroupName != null &&
                    this.GroupName.Equals(input.GroupName))
                ) && 
                (
                    this.ParentKey == input.ParentKey ||
                    (this.ParentKey != null &&
                    this.ParentKey.Equals(input.ParentKey))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.NumOrganizers == input.NumOrganizers ||
                    (this.NumOrganizers != null &&
                    this.NumOrganizers.Equals(input.NumOrganizers))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Groupkey != null)
                    hashCode = hashCode * 59 + this.Groupkey.GetHashCode();
                if (this.GroupName != null)
                    hashCode = hashCode * 59 + this.GroupName.GetHashCode();
                if (this.ParentKey != null)
                    hashCode = hashCode * 59 + this.ParentKey.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.NumOrganizers != null)
                    hashCode = hashCode * 59 + this.NumOrganizers.GetHashCode();
                return hashCode;
            }
        }
    }

}
