/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes a historical meeting within specified dates.
    /// </summary>
    [DataContract]
    public partial class HistoricalMeeting :  IEquatable<HistoricalMeeting>
    {
        /// <summary>
        /// The meeting type
        /// </summary>
        /// <value>The meeting type</value>
        [DataMember(Name="meetingType", EmitDefaultValue=false)]
        public MeetingType MeetingType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricalMeeting" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HistoricalMeeting() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricalMeeting" /> class.
        /// </summary>
        /// <param name="startTime">The time the meeting instance started (required).</param>
        /// <param name="lastName">The surname of the meeting organizer (required).</param>
        /// <param name="duration">The duration of the meeting session in minutes (required).</param>
        /// <param name="numAttendees">The number of attendees at the meeting instance (required).</param>
        /// <param name="accountKey">The key of the company account (required).</param>
        /// <param name="email">The meeting organizer&#39;s email address (required).</param>
        /// <param name="sessionId">The ID of the meeting session (required).</param>
        /// <param name="subject">The subject of the meeting (required).</param>
        /// <param name="locale">The current language setting of the organizer in the web portal (required).</param>
        /// <param name="organizerKey">The key of the meeting organizer (required).</param>
        /// <param name="meetingId">The meeting ID (required).</param>
        /// <param name="meetingType">The meeting type (required).</param>
        /// <param name="firstName">The meeting organizer&#39;s first name (required).</param>
        /// <param name="endTime">The time the meeting instance ended (required).</param>
        /// <param name="conferenceCallInfo">Audio options for the meeting (required).</param>
        /// <param name="recording">Information about the meeting recording.</param>
        public HistoricalMeeting(DateTime? startTime = default(DateTime?), string lastName = default(string), string duration = default(string), string numAttendees = default(string), string accountKey = default(string), string email = default(string), string sessionId = default(string), string subject = default(string), string locale = default(string), string organizerKey = default(string), string meetingId = default(string), MeetingType meetingType = default(MeetingType), string firstName = default(string), DateTime? endTime = default(DateTime?), string conferenceCallInfo = default(string), MeetingRecording recording = default(MeetingRecording))
        {
            // to ensure "startTime" is required (not null)
            if (startTime == null)
            {
                throw new InvalidDataException("startTime is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.StartTime = startTime;
            }
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new InvalidDataException("lastName is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.LastName = lastName;
            }
            // to ensure "duration" is required (not null)
            if (duration == null)
            {
                throw new InvalidDataException("duration is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.Duration = duration;
            }
            // to ensure "numAttendees" is required (not null)
            if (numAttendees == null)
            {
                throw new InvalidDataException("numAttendees is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.NumAttendees = numAttendees;
            }
            // to ensure "accountKey" is required (not null)
            if (accountKey == null)
            {
                throw new InvalidDataException("accountKey is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.AccountKey = accountKey;
            }
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "sessionId" is required (not null)
            if (sessionId == null)
            {
                throw new InvalidDataException("sessionId is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.SessionId = sessionId;
            }
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new InvalidDataException("subject is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.Subject = subject;
            }
            // to ensure "locale" is required (not null)
            if (locale == null)
            {
                throw new InvalidDataException("locale is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.Locale = locale;
            }
            // to ensure "organizerKey" is required (not null)
            if (organizerKey == null)
            {
                throw new InvalidDataException("organizerKey is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.OrganizerKey = organizerKey;
            }
            // to ensure "meetingId" is required (not null)
            if (meetingId == null)
            {
                throw new InvalidDataException("meetingId is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.MeetingId = meetingId;
            }
            // to ensure "meetingType" is required (not null)
            if (meetingType == null)
            {
                throw new InvalidDataException("meetingType is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.MeetingType = meetingType;
            }
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new InvalidDataException("firstName is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.FirstName = firstName;
            }
            // to ensure "endTime" is required (not null)
            if (endTime == null)
            {
                throw new InvalidDataException("endTime is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.EndTime = endTime;
            }
            // to ensure "conferenceCallInfo" is required (not null)
            if (conferenceCallInfo == null)
            {
                throw new InvalidDataException("conferenceCallInfo is a required property for HistoricalMeeting and cannot be null");
            }
            else
            {
                this.ConferenceCallInfo = conferenceCallInfo;
            }
            this.Recording = recording;
        }
        
        /// <summary>
        /// The time the meeting instance started
        /// </summary>
        /// <value>The time the meeting instance started</value>
        [DataMember(Name="startTime", EmitDefaultValue=false)]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// The surname of the meeting organizer
        /// </summary>
        /// <value>The surname of the meeting organizer</value>
        [DataMember(Name="lastName", EmitDefaultValue=false)]
        public string LastName { get; set; }

        /// <summary>
        /// The duration of the meeting session in minutes
        /// </summary>
        /// <value>The duration of the meeting session in minutes</value>
        [DataMember(Name="duration", EmitDefaultValue=false)]
        public string Duration { get; set; }

        /// <summary>
        /// The number of attendees at the meeting instance
        /// </summary>
        /// <value>The number of attendees at the meeting instance</value>
        [DataMember(Name="numAttendees", EmitDefaultValue=false)]
        public string NumAttendees { get; set; }

        /// <summary>
        /// The key of the company account
        /// </summary>
        /// <value>The key of the company account</value>
        [DataMember(Name="accountKey", EmitDefaultValue=false)]
        public string AccountKey { get; set; }

        /// <summary>
        /// The meeting organizer&#39;s email address
        /// </summary>
        /// <value>The meeting organizer&#39;s email address</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// The ID of the meeting session
        /// </summary>
        /// <value>The ID of the meeting session</value>
        [DataMember(Name="sessionId", EmitDefaultValue=false)]
        public string SessionId { get; set; }

        /// <summary>
        /// The subject of the meeting
        /// </summary>
        /// <value>The subject of the meeting</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// The current language setting of the organizer in the web portal
        /// </summary>
        /// <value>The current language setting of the organizer in the web portal</value>
        [DataMember(Name="locale", EmitDefaultValue=false)]
        public string Locale { get; set; }

        /// <summary>
        /// The key of the meeting organizer
        /// </summary>
        /// <value>The key of the meeting organizer</value>
        [DataMember(Name="organizerKey", EmitDefaultValue=false)]
        public string OrganizerKey { get; set; }

        /// <summary>
        /// The meeting ID
        /// </summary>
        /// <value>The meeting ID</value>
        [DataMember(Name="meetingId", EmitDefaultValue=false)]
        public string MeetingId { get; set; }


        /// <summary>
        /// The meeting organizer&#39;s first name
        /// </summary>
        /// <value>The meeting organizer&#39;s first name</value>
        [DataMember(Name="firstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// The time the meeting instance ended
        /// </summary>
        /// <value>The time the meeting instance ended</value>
        [DataMember(Name="endTime", EmitDefaultValue=false)]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// Audio options for the meeting
        /// </summary>
        /// <value>Audio options for the meeting</value>
        [DataMember(Name="conferenceCallInfo", EmitDefaultValue=false)]
        public string ConferenceCallInfo { get; set; }

        /// <summary>
        /// Information about the meeting recording
        /// </summary>
        /// <value>Information about the meeting recording</value>
        [DataMember(Name="recording", EmitDefaultValue=false)]
        public MeetingRecording Recording { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HistoricalMeeting {\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  NumAttendees: ").Append(NumAttendees).Append("\n");
            sb.Append("  AccountKey: ").Append(AccountKey).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  OrganizerKey: ").Append(OrganizerKey).Append("\n");
            sb.Append("  MeetingId: ").Append(MeetingId).Append("\n");
            sb.Append("  MeetingType: ").Append(MeetingType).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  ConferenceCallInfo: ").Append(ConferenceCallInfo).Append("\n");
            sb.Append("  Recording: ").Append(Recording).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HistoricalMeeting);
        }

        /// <summary>
        /// Returns true if HistoricalMeeting instances are equal
        /// </summary>
        /// <param name="input">Instance of HistoricalMeeting to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HistoricalMeeting input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.Duration == input.Duration ||
                    (this.Duration != null &&
                    this.Duration.Equals(input.Duration))
                ) && 
                (
                    this.NumAttendees == input.NumAttendees ||
                    (this.NumAttendees != null &&
                    this.NumAttendees.Equals(input.NumAttendees))
                ) && 
                (
                    this.AccountKey == input.AccountKey ||
                    (this.AccountKey != null &&
                    this.AccountKey.Equals(input.AccountKey))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.SessionId == input.SessionId ||
                    (this.SessionId != null &&
                    this.SessionId.Equals(input.SessionId))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.Locale == input.Locale ||
                    (this.Locale != null &&
                    this.Locale.Equals(input.Locale))
                ) && 
                (
                    this.OrganizerKey == input.OrganizerKey ||
                    (this.OrganizerKey != null &&
                    this.OrganizerKey.Equals(input.OrganizerKey))
                ) && 
                (
                    this.MeetingId == input.MeetingId ||
                    (this.MeetingId != null &&
                    this.MeetingId.Equals(input.MeetingId))
                ) && 
                (
                    this.MeetingType == input.MeetingType ||
                    (this.MeetingType != null &&
                    this.MeetingType.Equals(input.MeetingType))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.EndTime == input.EndTime ||
                    (this.EndTime != null &&
                    this.EndTime.Equals(input.EndTime))
                ) && 
                (
                    this.ConferenceCallInfo == input.ConferenceCallInfo ||
                    (this.ConferenceCallInfo != null &&
                    this.ConferenceCallInfo.Equals(input.ConferenceCallInfo))
                ) && 
                (
                    this.Recording == input.Recording ||
                    (this.Recording != null &&
                    this.Recording.Equals(input.Recording))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StartTime != null)
                    hashCode = hashCode * 59 + this.StartTime.GetHashCode();
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.Duration != null)
                    hashCode = hashCode * 59 + this.Duration.GetHashCode();
                if (this.NumAttendees != null)
                    hashCode = hashCode * 59 + this.NumAttendees.GetHashCode();
                if (this.AccountKey != null)
                    hashCode = hashCode * 59 + this.AccountKey.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.SessionId != null)
                    hashCode = hashCode * 59 + this.SessionId.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.Locale != null)
                    hashCode = hashCode * 59 + this.Locale.GetHashCode();
                if (this.OrganizerKey != null)
                    hashCode = hashCode * 59 + this.OrganizerKey.GetHashCode();
                if (this.MeetingId != null)
                    hashCode = hashCode * 59 + this.MeetingId.GetHashCode();
                if (this.MeetingType != null)
                    hashCode = hashCode * 59 + this.MeetingType.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.EndTime != null)
                    hashCode = hashCode * 59 + this.EndTime.GetHashCode();
                if (this.ConferenceCallInfo != null)
                    hashCode = hashCode * 59 + this.ConferenceCallInfo.GetHashCode();
                if (this.Recording != null)
                    hashCode = hashCode * 59 + this.Recording.GetHashCode();
                return hashCode;
            }
        }
    }

}
