/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes a given meeting.
    /// </summary>
    [DataContract]
    public partial class MeetingById :  IEquatable<MeetingById>
    {
        /// <summary>
        /// The meeting status, i.e whether the meeting is running or not
        /// </summary>
        /// <value>The meeting status, i.e whether the meeting is running or not</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public MeetingStatus Status { get; set; }
        /// <summary>
        /// The meeting type
        /// </summary>
        /// <value>The meeting type</value>
        [DataMember(Name="meetingType", EmitDefaultValue=false)]
        public MeetingType MeetingType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeetingById" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MeetingById() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeetingById" /> class.
        /// </summary>
        /// <param name="createTime">DEPRECATED. Returns an empty string &#39;&#39; (required).</param>
        /// <param name="passwordRequired">Indicates whether a password is required to join the meeting (required).</param>
        /// <param name="status">The meeting status, i.e whether the meeting is running or not (required).</param>
        /// <param name="subject">The subject of the meeting (required).</param>
        /// <param name="endTime">The ending time of the meeting (required).</param>
        /// <param name="conferenceCallInfo">Audio options of the meeting (required).</param>
        /// <param name="startTime">The meeting starting time (required).</param>
        /// <param name="duration">The duration of the meeting in minutes (required).</param>
        /// <param name="maxParticipants">The maximum number of participants allowed at the meeting (required).</param>
        /// <param name="meetingId">The meeting ID (required).</param>
        /// <param name="meetingKey">The meeting ID. Field retained for backwards compatibility reasons (required).</param>
        /// <param name="meetingType">The meeting type (required).</param>
        /// <param name="uniqueMeetingId">The meeting ID. Field retained for backwards compatibility reasons (required).</param>
        /// <param name="coorganizerKeys">The co-organizer keys of users that also can host the meeting..</param>
        public MeetingById(DateTime? createTime = default(DateTime?), bool? passwordRequired = default(bool?), MeetingStatus status = default(MeetingStatus), string subject = default(string), DateTime? endTime = default(DateTime?), string conferenceCallInfo = default(string), DateTime? startTime = default(DateTime?), int? duration = default(int?), int? maxParticipants = default(int?), long? meetingId = default(long?), long? meetingKey = default(long?), MeetingType meetingType = default(MeetingType), long? uniqueMeetingId = default(long?), List<string> coorganizerKeys = default(List<string>))
        {
            // to ensure "createTime" is required (not null)
            if (createTime == null)
            {
                throw new InvalidDataException("createTime is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.CreateTime = createTime;
            }
            // to ensure "passwordRequired" is required (not null)
            if (passwordRequired == null)
            {
                throw new InvalidDataException("passwordRequired is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.PasswordRequired = passwordRequired;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new InvalidDataException("subject is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.Subject = subject;
            }
            // to ensure "endTime" is required (not null)
            if (endTime == null)
            {
                throw new InvalidDataException("endTime is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.EndTime = endTime;
            }
            // to ensure "conferenceCallInfo" is required (not null)
            if (conferenceCallInfo == null)
            {
                throw new InvalidDataException("conferenceCallInfo is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.ConferenceCallInfo = conferenceCallInfo;
            }
            // to ensure "startTime" is required (not null)
            if (startTime == null)
            {
                throw new InvalidDataException("startTime is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.StartTime = startTime;
            }
            // to ensure "duration" is required (not null)
            if (duration == null)
            {
                throw new InvalidDataException("duration is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.Duration = duration;
            }
            // to ensure "maxParticipants" is required (not null)
            if (maxParticipants == null)
            {
                throw new InvalidDataException("maxParticipants is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.MaxParticipants = maxParticipants;
            }
            // to ensure "meetingId" is required (not null)
            if (meetingId == null)
            {
                throw new InvalidDataException("meetingId is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.MeetingId = meetingId;
            }
            // to ensure "meetingKey" is required (not null)
            if (meetingKey == null)
            {
                throw new InvalidDataException("meetingKey is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.MeetingKey = meetingKey;
            }
            // to ensure "meetingType" is required (not null)
            if (meetingType == null)
            {
                throw new InvalidDataException("meetingType is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.MeetingType = meetingType;
            }
            // to ensure "uniqueMeetingId" is required (not null)
            if (uniqueMeetingId == null)
            {
                throw new InvalidDataException("uniqueMeetingId is a required property for MeetingById and cannot be null");
            }
            else
            {
                this.UniqueMeetingId = uniqueMeetingId;
            }
            this.CoorganizerKeys = coorganizerKeys;
        }
        
        /// <summary>
        /// DEPRECATED. Returns an empty string &#39;&#39;
        /// </summary>
        /// <value>DEPRECATED. Returns an empty string &#39;&#39;</value>
        [DataMember(Name="createTime", EmitDefaultValue=false)]
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// Indicates whether a password is required to join the meeting
        /// </summary>
        /// <value>Indicates whether a password is required to join the meeting</value>
        [DataMember(Name="passwordRequired", EmitDefaultValue=false)]
        public bool? PasswordRequired { get; set; }


        /// <summary>
        /// The subject of the meeting
        /// </summary>
        /// <value>The subject of the meeting</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// The ending time of the meeting
        /// </summary>
        /// <value>The ending time of the meeting</value>
        [DataMember(Name="endTime", EmitDefaultValue=false)]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// Audio options of the meeting
        /// </summary>
        /// <value>Audio options of the meeting</value>
        [DataMember(Name="conferenceCallInfo", EmitDefaultValue=false)]
        public string ConferenceCallInfo { get; set; }

        /// <summary>
        /// The meeting starting time
        /// </summary>
        /// <value>The meeting starting time</value>
        [DataMember(Name="startTime", EmitDefaultValue=false)]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// The duration of the meeting in minutes
        /// </summary>
        /// <value>The duration of the meeting in minutes</value>
        [DataMember(Name="duration", EmitDefaultValue=false)]
        public int? Duration { get; set; }

        /// <summary>
        /// The maximum number of participants allowed at the meeting
        /// </summary>
        /// <value>The maximum number of participants allowed at the meeting</value>
        [DataMember(Name="maxParticipants", EmitDefaultValue=false)]
        public int? MaxParticipants { get; set; }

        /// <summary>
        /// The meeting ID
        /// </summary>
        /// <value>The meeting ID</value>
        [DataMember(Name="meetingId", EmitDefaultValue=false)]
        public long? MeetingId { get; set; }

        /// <summary>
        /// The meeting ID. Field retained for backwards compatibility reasons
        /// </summary>
        /// <value>The meeting ID. Field retained for backwards compatibility reasons</value>
        [DataMember(Name="meetingKey", EmitDefaultValue=false)]
        public long? MeetingKey { get; set; }


        /// <summary>
        /// The meeting ID. Field retained for backwards compatibility reasons
        /// </summary>
        /// <value>The meeting ID. Field retained for backwards compatibility reasons</value>
        [DataMember(Name="uniqueMeetingId", EmitDefaultValue=false)]
        public long? UniqueMeetingId { get; set; }

        /// <summary>
        /// The co-organizer keys of users that also can host the meeting.
        /// </summary>
        /// <value>The co-organizer keys of users that also can host the meeting.</value>
        [DataMember(Name="coorganizerKeys", EmitDefaultValue=false)]
        public List<string> CoorganizerKeys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MeetingById {\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  PasswordRequired: ").Append(PasswordRequired).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  ConferenceCallInfo: ").Append(ConferenceCallInfo).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  MaxParticipants: ").Append(MaxParticipants).Append("\n");
            sb.Append("  MeetingId: ").Append(MeetingId).Append("\n");
            sb.Append("  MeetingKey: ").Append(MeetingKey).Append("\n");
            sb.Append("  MeetingType: ").Append(MeetingType).Append("\n");
            sb.Append("  UniqueMeetingId: ").Append(UniqueMeetingId).Append("\n");
            sb.Append("  CoorganizerKeys: ").Append(CoorganizerKeys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MeetingById);
        }

        /// <summary>
        /// Returns true if MeetingById instances are equal
        /// </summary>
        /// <param name="input">Instance of MeetingById to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MeetingById input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CreateTime == input.CreateTime ||
                    (this.CreateTime != null &&
                    this.CreateTime.Equals(input.CreateTime))
                ) && 
                (
                    this.PasswordRequired == input.PasswordRequired ||
                    (this.PasswordRequired != null &&
                    this.PasswordRequired.Equals(input.PasswordRequired))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.EndTime == input.EndTime ||
                    (this.EndTime != null &&
                    this.EndTime.Equals(input.EndTime))
                ) && 
                (
                    this.ConferenceCallInfo == input.ConferenceCallInfo ||
                    (this.ConferenceCallInfo != null &&
                    this.ConferenceCallInfo.Equals(input.ConferenceCallInfo))
                ) && 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.Duration == input.Duration ||
                    (this.Duration != null &&
                    this.Duration.Equals(input.Duration))
                ) && 
                (
                    this.MaxParticipants == input.MaxParticipants ||
                    (this.MaxParticipants != null &&
                    this.MaxParticipants.Equals(input.MaxParticipants))
                ) && 
                (
                    this.MeetingId == input.MeetingId ||
                    (this.MeetingId != null &&
                    this.MeetingId.Equals(input.MeetingId))
                ) && 
                (
                    this.MeetingKey == input.MeetingKey ||
                    (this.MeetingKey != null &&
                    this.MeetingKey.Equals(input.MeetingKey))
                ) && 
                (
                    this.MeetingType == input.MeetingType ||
                    (this.MeetingType != null &&
                    this.MeetingType.Equals(input.MeetingType))
                ) && 
                (
                    this.UniqueMeetingId == input.UniqueMeetingId ||
                    (this.UniqueMeetingId != null &&
                    this.UniqueMeetingId.Equals(input.UniqueMeetingId))
                ) && 
                (
                    this.CoorganizerKeys == input.CoorganizerKeys ||
                    this.CoorganizerKeys != null &&
                    this.CoorganizerKeys.SequenceEqual(input.CoorganizerKeys)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CreateTime != null)
                    hashCode = hashCode * 59 + this.CreateTime.GetHashCode();
                if (this.PasswordRequired != null)
                    hashCode = hashCode * 59 + this.PasswordRequired.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.EndTime != null)
                    hashCode = hashCode * 59 + this.EndTime.GetHashCode();
                if (this.ConferenceCallInfo != null)
                    hashCode = hashCode * 59 + this.ConferenceCallInfo.GetHashCode();
                if (this.StartTime != null)
                    hashCode = hashCode * 59 + this.StartTime.GetHashCode();
                if (this.Duration != null)
                    hashCode = hashCode * 59 + this.Duration.GetHashCode();
                if (this.MaxParticipants != null)
                    hashCode = hashCode * 59 + this.MaxParticipants.GetHashCode();
                if (this.MeetingId != null)
                    hashCode = hashCode * 59 + this.MeetingId.GetHashCode();
                if (this.MeetingKey != null)
                    hashCode = hashCode * 59 + this.MeetingKey.GetHashCode();
                if (this.MeetingType != null)
                    hashCode = hashCode * 59 + this.MeetingType.GetHashCode();
                if (this.UniqueMeetingId != null)
                    hashCode = hashCode * 59 + this.UniqueMeetingId.GetHashCode();
                if (this.CoorganizerKeys != null)
                    hashCode = hashCode * 59 + this.CoorganizerKeys.GetHashCode();
                return hashCode;
            }
        }
    }

}
