/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes a newly created meeting.
    /// </summary>
    [DataContract]
    public partial class MeetingCreated :  IEquatable<MeetingCreated>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MeetingCreated" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MeetingCreated() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeetingCreated" /> class.
        /// </summary>
        /// <param name="joinURL">The URL the meeting participants will use to join the meeting (required).</param>
        /// <param name="meetingid">The meeting ID (required).</param>
        /// <param name="maxParticipants">The maximum number of participants allowed in the meeting (required).</param>
        /// <param name="uniqueMeetingId">The meeting ID. Field retained for backwards compatibility reasons (required).</param>
        /// <param name="conferenceCallInfo">Audio options for the meeting (required).</param>
        public MeetingCreated(string joinURL = default(string), long? meetingid = default(long?), int? maxParticipants = default(int?), long? uniqueMeetingId = default(long?), string conferenceCallInfo = default(string))
        {
            // to ensure "joinURL" is required (not null)
            if (joinURL == null)
            {
                throw new InvalidDataException("joinURL is a required property for MeetingCreated and cannot be null");
            }
            else
            {
                this.JoinURL = joinURL;
            }
            // to ensure "meetingid" is required (not null)
            if (meetingid == null)
            {
                throw new InvalidDataException("meetingid is a required property for MeetingCreated and cannot be null");
            }
            else
            {
                this.Meetingid = meetingid;
            }
            // to ensure "maxParticipants" is required (not null)
            if (maxParticipants == null)
            {
                throw new InvalidDataException("maxParticipants is a required property for MeetingCreated and cannot be null");
            }
            else
            {
                this.MaxParticipants = maxParticipants;
            }
            // to ensure "uniqueMeetingId" is required (not null)
            if (uniqueMeetingId == null)
            {
                throw new InvalidDataException("uniqueMeetingId is a required property for MeetingCreated and cannot be null");
            }
            else
            {
                this.UniqueMeetingId = uniqueMeetingId;
            }
            // to ensure "conferenceCallInfo" is required (not null)
            if (conferenceCallInfo == null)
            {
                throw new InvalidDataException("conferenceCallInfo is a required property for MeetingCreated and cannot be null");
            }
            else
            {
                this.ConferenceCallInfo = conferenceCallInfo;
            }
        }
        
        /// <summary>
        /// The URL the meeting participants will use to join the meeting
        /// </summary>
        /// <value>The URL the meeting participants will use to join the meeting</value>
        [DataMember(Name="joinURL", EmitDefaultValue=false)]
        public string JoinURL { get; set; }

        /// <summary>
        /// The meeting ID
        /// </summary>
        /// <value>The meeting ID</value>
        [DataMember(Name="meetingid", EmitDefaultValue=false)]
        public long? Meetingid { get; set; }

        /// <summary>
        /// The maximum number of participants allowed in the meeting
        /// </summary>
        /// <value>The maximum number of participants allowed in the meeting</value>
        [DataMember(Name="maxParticipants", EmitDefaultValue=false)]
        public int? MaxParticipants { get; set; }

        /// <summary>
        /// The meeting ID. Field retained for backwards compatibility reasons
        /// </summary>
        /// <value>The meeting ID. Field retained for backwards compatibility reasons</value>
        [DataMember(Name="uniqueMeetingId", EmitDefaultValue=false)]
        public long? UniqueMeetingId { get; set; }

        /// <summary>
        /// Audio options for the meeting
        /// </summary>
        /// <value>Audio options for the meeting</value>
        [DataMember(Name="conferenceCallInfo", EmitDefaultValue=false)]
        public string ConferenceCallInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MeetingCreated {\n");
            sb.Append("  JoinURL: ").Append(JoinURL).Append("\n");
            sb.Append("  Meetingid: ").Append(Meetingid).Append("\n");
            sb.Append("  MaxParticipants: ").Append(MaxParticipants).Append("\n");
            sb.Append("  UniqueMeetingId: ").Append(UniqueMeetingId).Append("\n");
            sb.Append("  ConferenceCallInfo: ").Append(ConferenceCallInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MeetingCreated);
        }

        /// <summary>
        /// Returns true if MeetingCreated instances are equal
        /// </summary>
        /// <param name="input">Instance of MeetingCreated to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MeetingCreated input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.JoinURL == input.JoinURL ||
                    (this.JoinURL != null &&
                    this.JoinURL.Equals(input.JoinURL))
                ) && 
                (
                    this.Meetingid == input.Meetingid ||
                    (this.Meetingid != null &&
                    this.Meetingid.Equals(input.Meetingid))
                ) && 
                (
                    this.MaxParticipants == input.MaxParticipants ||
                    (this.MaxParticipants != null &&
                    this.MaxParticipants.Equals(input.MaxParticipants))
                ) && 
                (
                    this.UniqueMeetingId == input.UniqueMeetingId ||
                    (this.UniqueMeetingId != null &&
                    this.UniqueMeetingId.Equals(input.UniqueMeetingId))
                ) && 
                (
                    this.ConferenceCallInfo == input.ConferenceCallInfo ||
                    (this.ConferenceCallInfo != null &&
                    this.ConferenceCallInfo.Equals(input.ConferenceCallInfo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.JoinURL != null)
                    hashCode = hashCode * 59 + this.JoinURL.GetHashCode();
                if (this.Meetingid != null)
                    hashCode = hashCode * 59 + this.Meetingid.GetHashCode();
                if (this.MaxParticipants != null)
                    hashCode = hashCode * 59 + this.MaxParticipants.GetHashCode();
                if (this.UniqueMeetingId != null)
                    hashCode = hashCode * 59 + this.UniqueMeetingId.GetHashCode();
                if (this.ConferenceCallInfo != null)
                    hashCode = hashCode * 59 + this.ConferenceCallInfo.GetHashCode();
                return hashCode;
            }
        }
    }

}
