/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes a unique past meeting instance.
    /// </summary>
    [DataContract]
    public partial class MeetingHistory :  IEquatable<MeetingHistory>
    {
        /// <summary>
        /// The meeting type
        /// </summary>
        /// <value>The meeting type</value>
        [DataMember(Name="meetingType", EmitDefaultValue=false)]
        public MeetingType MeetingType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeetingHistory" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MeetingHistory() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeetingHistory" /> class.
        /// </summary>
        /// <param name="lastName">The surname of the meeting organizer (required).</param>
        /// <param name="groupName">DEPRECATED. An empty string &#39;&#39; is returned (required).</param>
        /// <param name="numAttendees">The number of attendees at the meeting instance (required).</param>
        /// <param name="passwordRequired">DEPRECATED. An empty string &#39;&#39; is returned (required).</param>
        /// <param name="status">DEPRECATED. An empty string &#39;&#39; is returned (required).</param>
        /// <param name="subject">The subject of the meeting (required).</param>
        /// <param name="endTime">The time the meeting instance ended (required).</param>
        /// <param name="date">The time the meeting instance started. Field retained for backwards compatibility reasons (required).</param>
        /// <param name="conferenceCallInfo">Audio options for the meeting (required).</param>
        /// <param name="startTime">The time the meeting instance started (required).</param>
        /// <param name="organizerkey">The key of the meeting organizer. Field retained for backwards compatibility reasons (required).</param>
        /// <param name="meetingInstanceKey">The key of the unique meeting instance (required).</param>
        /// <param name="newOrganizerKey">The key of the meeting organizer. Field introduced for compatibility reasons (required).</param>
        /// <param name="duration">The duration of the meeting session in minutes (required).</param>
        /// <param name="newMeetingId">Formatted meeting ID (required).</param>
        /// <param name="sessionId">The ID of the meeting session (required).</param>
        /// <param name="email">The meeting organizer&#39;s email address (required).</param>
        /// <param name="meetingId">The meeting ID (required).</param>
        /// <param name="organizerKey">The key of the meeting organizer (required).</param>
        /// <param name="meetingKey">The meeting ID. Field retained for backwards compatibility reasons (required).</param>
        /// <param name="meetingType">The meeting type (required).</param>
        /// <param name="firstName">The meeting organizer&#39;s first name (required).</param>
        /// <param name="uniqueMeetingId">The meeting ID. Field retained for backwards compatibility reasons (required).</param>
        /// <param name="recording">Information about the meeting recording.</param>
        public MeetingHistory(string lastName = default(string), string groupName = default(string), int? numAttendees = default(int?), bool? passwordRequired = default(bool?), string status = default(string), string subject = default(string), DateTime? endTime = default(DateTime?), DateTime? date = default(DateTime?), string conferenceCallInfo = default(string), DateTime? startTime = default(DateTime?), string organizerkey = default(string), long? meetingInstanceKey = default(long?), string newOrganizerKey = default(string), int? duration = default(int?), string newMeetingId = default(string), long? sessionId = default(long?), string email = default(string), long? meetingId = default(long?), string organizerKey = default(string), long? meetingKey = default(long?), MeetingType meetingType = default(MeetingType), string firstName = default(string), long? uniqueMeetingId = default(long?), MeetingRecording recording = default(MeetingRecording))
        {
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new InvalidDataException("lastName is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.LastName = lastName;
            }
            // to ensure "groupName" is required (not null)
            if (groupName == null)
            {
                throw new InvalidDataException("groupName is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.GroupName = groupName;
            }
            // to ensure "numAttendees" is required (not null)
            if (numAttendees == null)
            {
                throw new InvalidDataException("numAttendees is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.NumAttendees = numAttendees;
            }
            // to ensure "passwordRequired" is required (not null)
            if (passwordRequired == null)
            {
                throw new InvalidDataException("passwordRequired is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.PasswordRequired = passwordRequired;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new InvalidDataException("subject is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.Subject = subject;
            }
            // to ensure "endTime" is required (not null)
            if (endTime == null)
            {
                throw new InvalidDataException("endTime is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.EndTime = endTime;
            }
            // to ensure "date" is required (not null)
            if (date == null)
            {
                throw new InvalidDataException("date is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.Date = date;
            }
            // to ensure "conferenceCallInfo" is required (not null)
            if (conferenceCallInfo == null)
            {
                throw new InvalidDataException("conferenceCallInfo is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.ConferenceCallInfo = conferenceCallInfo;
            }
            // to ensure "startTime" is required (not null)
            if (startTime == null)
            {
                throw new InvalidDataException("startTime is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.StartTime = startTime;
            }
            // to ensure "organizerkey" is required (not null)
            if (organizerkey == null)
            {
                throw new InvalidDataException("organizerkey is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.Organizerkey = organizerkey;
            }
            // to ensure "meetingInstanceKey" is required (not null)
            if (meetingInstanceKey == null)
            {
                throw new InvalidDataException("meetingInstanceKey is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.MeetingInstanceKey = meetingInstanceKey;
            }
            // to ensure "newOrganizerKey" is required (not null)
            if (newOrganizerKey == null)
            {
                throw new InvalidDataException("newOrganizerKey is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.NewOrganizerKey = newOrganizerKey;
            }
            // to ensure "duration" is required (not null)
            if (duration == null)
            {
                throw new InvalidDataException("duration is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.Duration = duration;
            }
            // to ensure "newMeetingId" is required (not null)
            if (newMeetingId == null)
            {
                throw new InvalidDataException("newMeetingId is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.NewMeetingId = newMeetingId;
            }
            // to ensure "sessionId" is required (not null)
            if (sessionId == null)
            {
                throw new InvalidDataException("sessionId is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.SessionId = sessionId;
            }
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "meetingId" is required (not null)
            if (meetingId == null)
            {
                throw new InvalidDataException("meetingId is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.MeetingId = meetingId;
            }
            // to ensure "organizerKey" is required (not null)
            if (organizerKey == null)
            {
                throw new InvalidDataException("organizerKey is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.OrganizerKey = organizerKey;
            }
            // to ensure "meetingKey" is required (not null)
            if (meetingKey == null)
            {
                throw new InvalidDataException("meetingKey is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.MeetingKey = meetingKey;
            }
            // to ensure "meetingType" is required (not null)
            if (meetingType == null)
            {
                throw new InvalidDataException("meetingType is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.MeetingType = meetingType;
            }
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new InvalidDataException("firstName is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.FirstName = firstName;
            }
            // to ensure "uniqueMeetingId" is required (not null)
            if (uniqueMeetingId == null)
            {
                throw new InvalidDataException("uniqueMeetingId is a required property for MeetingHistory and cannot be null");
            }
            else
            {
                this.UniqueMeetingId = uniqueMeetingId;
            }
            this.Recording = recording;
        }
        
        /// <summary>
        /// The surname of the meeting organizer
        /// </summary>
        /// <value>The surname of the meeting organizer</value>
        [DataMember(Name="lastName", EmitDefaultValue=false)]
        public string LastName { get; set; }

        /// <summary>
        /// DEPRECATED. An empty string &#39;&#39; is returned
        /// </summary>
        /// <value>DEPRECATED. An empty string &#39;&#39; is returned</value>
        [DataMember(Name="groupName", EmitDefaultValue=false)]
        public string GroupName { get; set; }

        /// <summary>
        /// The number of attendees at the meeting instance
        /// </summary>
        /// <value>The number of attendees at the meeting instance</value>
        [DataMember(Name="numAttendees", EmitDefaultValue=false)]
        public int? NumAttendees { get; set; }

        /// <summary>
        /// DEPRECATED. An empty string &#39;&#39; is returned
        /// </summary>
        /// <value>DEPRECATED. An empty string &#39;&#39; is returned</value>
        [DataMember(Name="passwordRequired", EmitDefaultValue=false)]
        public bool? PasswordRequired { get; set; }

        /// <summary>
        /// DEPRECATED. An empty string &#39;&#39; is returned
        /// </summary>
        /// <value>DEPRECATED. An empty string &#39;&#39; is returned</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// The subject of the meeting
        /// </summary>
        /// <value>The subject of the meeting</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// The time the meeting instance ended
        /// </summary>
        /// <value>The time the meeting instance ended</value>
        [DataMember(Name="endTime", EmitDefaultValue=false)]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// The time the meeting instance started. Field retained for backwards compatibility reasons
        /// </summary>
        /// <value>The time the meeting instance started. Field retained for backwards compatibility reasons</value>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Audio options for the meeting
        /// </summary>
        /// <value>Audio options for the meeting</value>
        [DataMember(Name="conferenceCallInfo", EmitDefaultValue=false)]
        public string ConferenceCallInfo { get; set; }

        /// <summary>
        /// The time the meeting instance started
        /// </summary>
        /// <value>The time the meeting instance started</value>
        [DataMember(Name="startTime", EmitDefaultValue=false)]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// The key of the meeting organizer. Field retained for backwards compatibility reasons
        /// </summary>
        /// <value>The key of the meeting organizer. Field retained for backwards compatibility reasons</value>
        [DataMember(Name="organizerkey", EmitDefaultValue=false)]
        public string Organizerkey { get; set; }

        /// <summary>
        /// The key of the unique meeting instance
        /// </summary>
        /// <value>The key of the unique meeting instance</value>
        [DataMember(Name="meetingInstanceKey", EmitDefaultValue=false)]
        public long? MeetingInstanceKey { get; set; }

        /// <summary>
        /// The key of the meeting organizer. Field introduced for compatibility reasons
        /// </summary>
        /// <value>The key of the meeting organizer. Field introduced for compatibility reasons</value>
        [DataMember(Name="newOrganizerKey", EmitDefaultValue=false)]
        public string NewOrganizerKey { get; set; }

        /// <summary>
        /// The duration of the meeting session in minutes
        /// </summary>
        /// <value>The duration of the meeting session in minutes</value>
        [DataMember(Name="duration", EmitDefaultValue=false)]
        public int? Duration { get; set; }

        /// <summary>
        /// Formatted meeting ID
        /// </summary>
        /// <value>Formatted meeting ID</value>
        [DataMember(Name="newMeetingId", EmitDefaultValue=false)]
        public string NewMeetingId { get; set; }

        /// <summary>
        /// The ID of the meeting session
        /// </summary>
        /// <value>The ID of the meeting session</value>
        [DataMember(Name="sessionId", EmitDefaultValue=false)]
        public long? SessionId { get; set; }

        /// <summary>
        /// The meeting organizer&#39;s email address
        /// </summary>
        /// <value>The meeting organizer&#39;s email address</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// The meeting ID
        /// </summary>
        /// <value>The meeting ID</value>
        [DataMember(Name="meetingId", EmitDefaultValue=false)]
        public long? MeetingId { get; set; }

        /// <summary>
        /// The key of the meeting organizer
        /// </summary>
        /// <value>The key of the meeting organizer</value>
        [DataMember(Name="organizerKey", EmitDefaultValue=false)]
        public string OrganizerKey { get; set; }

        /// <summary>
        /// The meeting ID. Field retained for backwards compatibility reasons
        /// </summary>
        /// <value>The meeting ID. Field retained for backwards compatibility reasons</value>
        [DataMember(Name="meetingKey", EmitDefaultValue=false)]
        public long? MeetingKey { get; set; }


        /// <summary>
        /// The meeting organizer&#39;s first name
        /// </summary>
        /// <value>The meeting organizer&#39;s first name</value>
        [DataMember(Name="firstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// The meeting ID. Field retained for backwards compatibility reasons
        /// </summary>
        /// <value>The meeting ID. Field retained for backwards compatibility reasons</value>
        [DataMember(Name="uniqueMeetingId", EmitDefaultValue=false)]
        public long? UniqueMeetingId { get; set; }

        /// <summary>
        /// Information about the meeting recording
        /// </summary>
        /// <value>Information about the meeting recording</value>
        [DataMember(Name="recording", EmitDefaultValue=false)]
        public MeetingRecording Recording { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MeetingHistory {\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("  NumAttendees: ").Append(NumAttendees).Append("\n");
            sb.Append("  PasswordRequired: ").Append(PasswordRequired).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  ConferenceCallInfo: ").Append(ConferenceCallInfo).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  Organizerkey: ").Append(Organizerkey).Append("\n");
            sb.Append("  MeetingInstanceKey: ").Append(MeetingInstanceKey).Append("\n");
            sb.Append("  NewOrganizerKey: ").Append(NewOrganizerKey).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  NewMeetingId: ").Append(NewMeetingId).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  MeetingId: ").Append(MeetingId).Append("\n");
            sb.Append("  OrganizerKey: ").Append(OrganizerKey).Append("\n");
            sb.Append("  MeetingKey: ").Append(MeetingKey).Append("\n");
            sb.Append("  MeetingType: ").Append(MeetingType).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  UniqueMeetingId: ").Append(UniqueMeetingId).Append("\n");
            sb.Append("  Recording: ").Append(Recording).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MeetingHistory);
        }

        /// <summary>
        /// Returns true if MeetingHistory instances are equal
        /// </summary>
        /// <param name="input">Instance of MeetingHistory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MeetingHistory input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.GroupName == input.GroupName ||
                    (this.GroupName != null &&
                    this.GroupName.Equals(input.GroupName))
                ) && 
                (
                    this.NumAttendees == input.NumAttendees ||
                    (this.NumAttendees != null &&
                    this.NumAttendees.Equals(input.NumAttendees))
                ) && 
                (
                    this.PasswordRequired == input.PasswordRequired ||
                    (this.PasswordRequired != null &&
                    this.PasswordRequired.Equals(input.PasswordRequired))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.EndTime == input.EndTime ||
                    (this.EndTime != null &&
                    this.EndTime.Equals(input.EndTime))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.ConferenceCallInfo == input.ConferenceCallInfo ||
                    (this.ConferenceCallInfo != null &&
                    this.ConferenceCallInfo.Equals(input.ConferenceCallInfo))
                ) && 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.Organizerkey == input.Organizerkey ||
                    (this.Organizerkey != null &&
                    this.Organizerkey.Equals(input.Organizerkey))
                ) && 
                (
                    this.MeetingInstanceKey == input.MeetingInstanceKey ||
                    (this.MeetingInstanceKey != null &&
                    this.MeetingInstanceKey.Equals(input.MeetingInstanceKey))
                ) && 
                (
                    this.NewOrganizerKey == input.NewOrganizerKey ||
                    (this.NewOrganizerKey != null &&
                    this.NewOrganizerKey.Equals(input.NewOrganizerKey))
                ) && 
                (
                    this.Duration == input.Duration ||
                    (this.Duration != null &&
                    this.Duration.Equals(input.Duration))
                ) && 
                (
                    this.NewMeetingId == input.NewMeetingId ||
                    (this.NewMeetingId != null &&
                    this.NewMeetingId.Equals(input.NewMeetingId))
                ) && 
                (
                    this.SessionId == input.SessionId ||
                    (this.SessionId != null &&
                    this.SessionId.Equals(input.SessionId))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.MeetingId == input.MeetingId ||
                    (this.MeetingId != null &&
                    this.MeetingId.Equals(input.MeetingId))
                ) && 
                (
                    this.OrganizerKey == input.OrganizerKey ||
                    (this.OrganizerKey != null &&
                    this.OrganizerKey.Equals(input.OrganizerKey))
                ) && 
                (
                    this.MeetingKey == input.MeetingKey ||
                    (this.MeetingKey != null &&
                    this.MeetingKey.Equals(input.MeetingKey))
                ) && 
                (
                    this.MeetingType == input.MeetingType ||
                    (this.MeetingType != null &&
                    this.MeetingType.Equals(input.MeetingType))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.UniqueMeetingId == input.UniqueMeetingId ||
                    (this.UniqueMeetingId != null &&
                    this.UniqueMeetingId.Equals(input.UniqueMeetingId))
                ) && 
                (
                    this.Recording == input.Recording ||
                    (this.Recording != null &&
                    this.Recording.Equals(input.Recording))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.GroupName != null)
                    hashCode = hashCode * 59 + this.GroupName.GetHashCode();
                if (this.NumAttendees != null)
                    hashCode = hashCode * 59 + this.NumAttendees.GetHashCode();
                if (this.PasswordRequired != null)
                    hashCode = hashCode * 59 + this.PasswordRequired.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.EndTime != null)
                    hashCode = hashCode * 59 + this.EndTime.GetHashCode();
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.ConferenceCallInfo != null)
                    hashCode = hashCode * 59 + this.ConferenceCallInfo.GetHashCode();
                if (this.StartTime != null)
                    hashCode = hashCode * 59 + this.StartTime.GetHashCode();
                if (this.Organizerkey != null)
                    hashCode = hashCode * 59 + this.Organizerkey.GetHashCode();
                if (this.MeetingInstanceKey != null)
                    hashCode = hashCode * 59 + this.MeetingInstanceKey.GetHashCode();
                if (this.NewOrganizerKey != null)
                    hashCode = hashCode * 59 + this.NewOrganizerKey.GetHashCode();
                if (this.Duration != null)
                    hashCode = hashCode * 59 + this.Duration.GetHashCode();
                if (this.NewMeetingId != null)
                    hashCode = hashCode * 59 + this.NewMeetingId.GetHashCode();
                if (this.SessionId != null)
                    hashCode = hashCode * 59 + this.SessionId.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.MeetingId != null)
                    hashCode = hashCode * 59 + this.MeetingId.GetHashCode();
                if (this.OrganizerKey != null)
                    hashCode = hashCode * 59 + this.OrganizerKey.GetHashCode();
                if (this.MeetingKey != null)
                    hashCode = hashCode * 59 + this.MeetingKey.GetHashCode();
                if (this.MeetingType != null)
                    hashCode = hashCode * 59 + this.MeetingType.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.UniqueMeetingId != null)
                    hashCode = hashCode * 59 + this.UniqueMeetingId.GetHashCode();
                if (this.Recording != null)
                    hashCode = hashCode * 59 + this.Recording.GetHashCode();
                return hashCode;
            }
        }
    }

}
