/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes the information required to update a meeting.
    /// </summary>
    [DataContract]
    public partial class MeetingReqUpdate :  IEquatable<MeetingReqUpdate>
    {
        /// <summary>
        /// The meeting type
        /// </summary>
        /// <value>The meeting type</value>
        [DataMember(Name="meetingtype", EmitDefaultValue=false)]
        public MeetingType Meetingtype { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeetingReqUpdate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MeetingReqUpdate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeetingReqUpdate" /> class.
        /// </summary>
        /// <param name="subject">A description of the meeting. 100 characters maximum. The characters &#39;&amp;gt;&#39; and &#39;&amp;lt;&#39; have to be replaced with the corresponding html character code (&amp;amp;gt; for &amp;#39;&amp;gt;&amp;#39; and &amp;amp;lt; for &amp;#39;&amp;lt;&amp;#39;) (required).</param>
        /// <param name="starttime">The starting time of the meeting. A required ISO8601 UTC string, e.g. 2015-07-01T22:00:00Z (required).</param>
        /// <param name="endtime">The ending time of the meeting. A required ISO8601 UTC string, e.g. 2015-07-01T22:00:00Z (required).</param>
        /// <param name="passwordrequired">Indicates whether a password is required to join the meeting. Required parameter (required).</param>
        /// <param name="conferencecallinfo">A required string. Can be one of the following options: &lt;br&gt;PSTN (PSTN only), &lt;br&gt;Free (PSTN and VoIP), &lt;br&gt;Hybrid, (PSTN and VoIP), &lt;br&gt;Private (you provide numbers and access code), or &lt;br&gt;VoIP (VoIP only). &lt;br&gt;You may also enter plain text for numbers and access codes with a limit of 255 characters (required).</param>
        /// <param name="timezonekey">DEPRECATED. Must be provided and set to empty string &#39;&#39; (required).</param>
        /// <param name="meetingtype">The meeting type (required).</param>
        /// <param name="coorganizerKeys">Co-organizer keys. Co-organizers can start the meeting on the organizers behalf. Retrieve a list of valid organizers from the \&quot;Get all organizers\&quot; call..</param>
        public MeetingReqUpdate(string subject = default(string), DateTime? starttime = default(DateTime?), DateTime? endtime = default(DateTime?), bool? passwordrequired = default(bool?), string conferencecallinfo = default(string), string timezonekey = default(string), MeetingType meetingtype = default(MeetingType), List<string> coorganizerKeys = default(List<string>))
        {
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new InvalidDataException("subject is a required property for MeetingReqUpdate and cannot be null");
            }
            else
            {
                this.Subject = subject;
            }
            // to ensure "starttime" is required (not null)
            if (starttime == null)
            {
                throw new InvalidDataException("starttime is a required property for MeetingReqUpdate and cannot be null");
            }
            else
            {
                this.Starttime = starttime;
            }
            // to ensure "endtime" is required (not null)
            if (endtime == null)
            {
                throw new InvalidDataException("endtime is a required property for MeetingReqUpdate and cannot be null");
            }
            else
            {
                this.Endtime = endtime;
            }
            // to ensure "passwordrequired" is required (not null)
            if (passwordrequired == null)
            {
                throw new InvalidDataException("passwordrequired is a required property for MeetingReqUpdate and cannot be null");
            }
            else
            {
                this.Passwordrequired = passwordrequired;
            }
            // to ensure "conferencecallinfo" is required (not null)
            if (conferencecallinfo == null)
            {
                throw new InvalidDataException("conferencecallinfo is a required property for MeetingReqUpdate and cannot be null");
            }
            else
            {
                this.Conferencecallinfo = conferencecallinfo;
            }
            // to ensure "timezonekey" is required (not null)
            if (timezonekey == null)
            {
                throw new InvalidDataException("timezonekey is a required property for MeetingReqUpdate and cannot be null");
            }
            else
            {
                this.Timezonekey = timezonekey;
            }
            // to ensure "meetingtype" is required (not null)
            if (meetingtype == null)
            {
                throw new InvalidDataException("meetingtype is a required property for MeetingReqUpdate and cannot be null");
            }
            else
            {
                this.Meetingtype = meetingtype;
            }
            this.CoorganizerKeys = coorganizerKeys;
        }
        
        /// <summary>
        /// A description of the meeting. 100 characters maximum. The characters &#39;&amp;gt;&#39; and &#39;&amp;lt;&#39; have to be replaced with the corresponding html character code (&amp;amp;gt; for &amp;#39;&amp;gt;&amp;#39; and &amp;amp;lt; for &amp;#39;&amp;lt;&amp;#39;)
        /// </summary>
        /// <value>A description of the meeting. 100 characters maximum. The characters &#39;&amp;gt;&#39; and &#39;&amp;lt;&#39; have to be replaced with the corresponding html character code (&amp;amp;gt; for &amp;#39;&amp;gt;&amp;#39; and &amp;amp;lt; for &amp;#39;&amp;lt;&amp;#39;)</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// The starting time of the meeting. A required ISO8601 UTC string, e.g. 2015-07-01T22:00:00Z
        /// </summary>
        /// <value>The starting time of the meeting. A required ISO8601 UTC string, e.g. 2015-07-01T22:00:00Z</value>
        [DataMember(Name="starttime", EmitDefaultValue=false)]
        public DateTime? Starttime { get; set; }

        /// <summary>
        /// The ending time of the meeting. A required ISO8601 UTC string, e.g. 2015-07-01T22:00:00Z
        /// </summary>
        /// <value>The ending time of the meeting. A required ISO8601 UTC string, e.g. 2015-07-01T22:00:00Z</value>
        [DataMember(Name="endtime", EmitDefaultValue=false)]
        public DateTime? Endtime { get; set; }

        /// <summary>
        /// Indicates whether a password is required to join the meeting. Required parameter
        /// </summary>
        /// <value>Indicates whether a password is required to join the meeting. Required parameter</value>
        [DataMember(Name="passwordrequired", EmitDefaultValue=false)]
        public bool? Passwordrequired { get; set; }

        /// <summary>
        /// A required string. Can be one of the following options: &lt;br&gt;PSTN (PSTN only), &lt;br&gt;Free (PSTN and VoIP), &lt;br&gt;Hybrid, (PSTN and VoIP), &lt;br&gt;Private (you provide numbers and access code), or &lt;br&gt;VoIP (VoIP only). &lt;br&gt;You may also enter plain text for numbers and access codes with a limit of 255 characters
        /// </summary>
        /// <value>A required string. Can be one of the following options: &lt;br&gt;PSTN (PSTN only), &lt;br&gt;Free (PSTN and VoIP), &lt;br&gt;Hybrid, (PSTN and VoIP), &lt;br&gt;Private (you provide numbers and access code), or &lt;br&gt;VoIP (VoIP only). &lt;br&gt;You may also enter plain text for numbers and access codes with a limit of 255 characters</value>
        [DataMember(Name="conferencecallinfo", EmitDefaultValue=false)]
        public string Conferencecallinfo { get; set; }

        /// <summary>
        /// DEPRECATED. Must be provided and set to empty string &#39;&#39;
        /// </summary>
        /// <value>DEPRECATED. Must be provided and set to empty string &#39;&#39;</value>
        [DataMember(Name="timezonekey", EmitDefaultValue=false)]
        public string Timezonekey { get; set; }


        /// <summary>
        /// Co-organizer keys. Co-organizers can start the meeting on the organizers behalf. Retrieve a list of valid organizers from the \&quot;Get all organizers\&quot; call.
        /// </summary>
        /// <value>Co-organizer keys. Co-organizers can start the meeting on the organizers behalf. Retrieve a list of valid organizers from the \&quot;Get all organizers\&quot; call.</value>
        [DataMember(Name="coorganizerKeys", EmitDefaultValue=false)]
        public List<string> CoorganizerKeys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MeetingReqUpdate {\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Starttime: ").Append(Starttime).Append("\n");
            sb.Append("  Endtime: ").Append(Endtime).Append("\n");
            sb.Append("  Passwordrequired: ").Append(Passwordrequired).Append("\n");
            sb.Append("  Conferencecallinfo: ").Append(Conferencecallinfo).Append("\n");
            sb.Append("  Timezonekey: ").Append(Timezonekey).Append("\n");
            sb.Append("  Meetingtype: ").Append(Meetingtype).Append("\n");
            sb.Append("  CoorganizerKeys: ").Append(CoorganizerKeys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MeetingReqUpdate);
        }

        /// <summary>
        /// Returns true if MeetingReqUpdate instances are equal
        /// </summary>
        /// <param name="input">Instance of MeetingReqUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MeetingReqUpdate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.Starttime == input.Starttime ||
                    (this.Starttime != null &&
                    this.Starttime.Equals(input.Starttime))
                ) && 
                (
                    this.Endtime == input.Endtime ||
                    (this.Endtime != null &&
                    this.Endtime.Equals(input.Endtime))
                ) && 
                (
                    this.Passwordrequired == input.Passwordrequired ||
                    (this.Passwordrequired != null &&
                    this.Passwordrequired.Equals(input.Passwordrequired))
                ) && 
                (
                    this.Conferencecallinfo == input.Conferencecallinfo ||
                    (this.Conferencecallinfo != null &&
                    this.Conferencecallinfo.Equals(input.Conferencecallinfo))
                ) && 
                (
                    this.Timezonekey == input.Timezonekey ||
                    (this.Timezonekey != null &&
                    this.Timezonekey.Equals(input.Timezonekey))
                ) && 
                (
                    this.Meetingtype == input.Meetingtype ||
                    (this.Meetingtype != null &&
                    this.Meetingtype.Equals(input.Meetingtype))
                ) && 
                (
                    this.CoorganizerKeys == input.CoorganizerKeys ||
                    this.CoorganizerKeys != null &&
                    this.CoorganizerKeys.SequenceEqual(input.CoorganizerKeys)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.Starttime != null)
                    hashCode = hashCode * 59 + this.Starttime.GetHashCode();
                if (this.Endtime != null)
                    hashCode = hashCode * 59 + this.Endtime.GetHashCode();
                if (this.Passwordrequired != null)
                    hashCode = hashCode * 59 + this.Passwordrequired.GetHashCode();
                if (this.Conferencecallinfo != null)
                    hashCode = hashCode * 59 + this.Conferencecallinfo.GetHashCode();
                if (this.Timezonekey != null)
                    hashCode = hashCode * 59 + this.Timezonekey.GetHashCode();
                if (this.Meetingtype != null)
                    hashCode = hashCode * 59 + this.Meetingtype.GetHashCode();
                if (this.CoorganizerKeys != null)
                    hashCode = hashCode * 59 + this.CoorganizerKeys.GetHashCode();
                return hashCode;
            }
        }
    }

}
