/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes a newly created organizer.
    /// </summary>
    [DataContract]
    public partial class OrganizerShort :  IEquatable<OrganizerShort>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizerShort" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrganizerShort() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizerShort" /> class.
        /// </summary>
        /// <param name="key">The organizer&#39;s key (required).</param>
        /// <param name="email">The organizer&#39;s email address (required).</param>
        public OrganizerShort(long? key = default(long?), string email = default(string))
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new InvalidDataException("key is a required property for OrganizerShort and cannot be null");
            }
            else
            {
                this.Key = key;
            }
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for OrganizerShort and cannot be null");
            }
            else
            {
                this.Email = email;
            }
        }
        
        /// <summary>
        /// The organizer&#39;s key
        /// </summary>
        /// <value>The organizer&#39;s key</value>
        [DataMember(Name="key", EmitDefaultValue=false)]
        public long? Key { get; set; }

        /// <summary>
        /// The organizer&#39;s email address
        /// </summary>
        /// <value>The organizer&#39;s email address</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrganizerShort {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrganizerShort);
        }

        /// <summary>
        /// Returns true if OrganizerShort instances are equal
        /// </summary>
        /// <param name="input">Instance of OrganizerShort to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrganizerShort input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Key == input.Key ||
                    (this.Key != null &&
                    this.Key.Equals(input.Key))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Key != null)
                    hashCode = hashCode * 59 + this.Key.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                return hashCode;
            }
        }
    }

}
