/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes the information required to create an organizer, with or without assigning a group.
    /// </summary>
    [DataContract]
    public partial class OrganizerReq :  IEquatable<OrganizerReq>
    {
        /// <summary>
        /// A product the organizer has access to, can be &#39;G2M&#39;, &#39;G2W&#39;, &#39;G2T&#39; or &#39;OPENVOICE&#39;
        /// </summary>
        /// <value>A product the organizer has access to, can be &#39;G2M&#39;, &#39;G2W&#39;, &#39;G2T&#39; or &#39;OPENVOICE&#39;</value>
        [DataMember(Name="productType", EmitDefaultValue=false)]
        public Product ProductType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizerReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrganizerReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizerReq" /> class.
        /// </summary>
        /// <param name="organizerEmail">The email address of the organizer (required).</param>
        /// <param name="firstName">The first name of the organizer (required).</param>
        /// <param name="lastName">The surname of the organizer (required).</param>
        /// <param name="productType">A product the organizer has access to, can be &#39;G2M&#39;, &#39;G2W&#39;, &#39;G2T&#39; or &#39;OPENVOICE&#39; (required).</param>
        public OrganizerReq(string organizerEmail = default(string), string firstName = default(string), string lastName = default(string), Product productType = default(Product))
        {
            // to ensure "organizerEmail" is required (not null)
            if (organizerEmail == null)
            {
                throw new InvalidDataException("organizerEmail is a required property for OrganizerReq and cannot be null");
            }
            else
            {
                this.OrganizerEmail = organizerEmail;
            }
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new InvalidDataException("firstName is a required property for OrganizerReq and cannot be null");
            }
            else
            {
                this.FirstName = firstName;
            }
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new InvalidDataException("lastName is a required property for OrganizerReq and cannot be null");
            }
            else
            {
                this.LastName = lastName;
            }
            // to ensure "productType" is required (not null)
            if (productType == null)
            {
                throw new InvalidDataException("productType is a required property for OrganizerReq and cannot be null");
            }
            else
            {
                this.ProductType = productType;
            }
        }
        
        /// <summary>
        /// The email address of the organizer
        /// </summary>
        /// <value>The email address of the organizer</value>
        [DataMember(Name="organizerEmail", EmitDefaultValue=false)]
        public string OrganizerEmail { get; set; }

        /// <summary>
        /// The first name of the organizer
        /// </summary>
        /// <value>The first name of the organizer</value>
        [DataMember(Name="firstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// The surname of the organizer
        /// </summary>
        /// <value>The surname of the organizer</value>
        [DataMember(Name="lastName", EmitDefaultValue=false)]
        public string LastName { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrganizerReq {\n");
            sb.Append("  OrganizerEmail: ").Append(OrganizerEmail).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  ProductType: ").Append(ProductType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrganizerReq);
        }

        /// <summary>
        /// Returns true if OrganizerReq instances are equal
        /// </summary>
        /// <param name="input">Instance of OrganizerReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrganizerReq input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OrganizerEmail == input.OrganizerEmail ||
                    (this.OrganizerEmail != null &&
                    this.OrganizerEmail.Equals(input.OrganizerEmail))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.ProductType == input.ProductType ||
                    (this.ProductType != null &&
                    this.ProductType.Equals(input.ProductType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrganizerEmail != null)
                    hashCode = hashCode * 59 + this.OrganizerEmail.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.ProductType != null)
                    hashCode = hashCode * 59 + this.ProductType.GetHashCode();
                return hashCode;
            }
        }
    }

}
