/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes an organizer within a specified group.
    /// </summary>
    [DataContract]
    public partial class OrganizerByGroup :  IEquatable<OrganizerByGroup>
    {
        /// <summary>
        /// The status of the organizer, i.e. whether the organizer is able to host meetings
        /// </summary>
        /// <value>The status of the organizer, i.e. whether the organizer is able to host meetings</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public Status Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizerByGroup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrganizerByGroup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizerByGroup" /> class.
        /// </summary>
        /// <param name="lastName">The organizer&#39;s surname (required).</param>
        /// <param name="groupId">The key of the group (required).</param>
        /// <param name="groupName">The name of the group (required).</param>
        /// <param name="status">The status of the organizer, i.e. whether the organizer is able to host meetings (required).</param>
        /// <param name="email">The organizer&#39;s email address (required).</param>
        /// <param name="organizerKey">The key of the organizer (required).</param>
        /// <param name="firstName">The organizer&#39;s first name (required).</param>
        /// <param name="products">The products the organizer has access to, can be &#39;G2M&#39;, &#39;G2W&#39;, &#39;G2T&#39; or &#39;OPENVOICE&#39; (required).</param>
        /// <param name="maxNumAttendeesAllowed">The maximum number of attendees allowed at sessions held by this organizer (required).</param>
        public OrganizerByGroup(string lastName = default(string), long? groupId = default(long?), string groupName = default(string), Status status = default(Status), string email = default(string), long? organizerKey = default(long?), string firstName = default(string), List<Product> products = default(List<Product>), int? maxNumAttendeesAllowed = default(int?))
        {
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new InvalidDataException("lastName is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.LastName = lastName;
            }
            // to ensure "groupId" is required (not null)
            if (groupId == null)
            {
                throw new InvalidDataException("groupId is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.GroupId = groupId;
            }
            // to ensure "groupName" is required (not null)
            if (groupName == null)
            {
                throw new InvalidDataException("groupName is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.GroupName = groupName;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "organizerKey" is required (not null)
            if (organizerKey == null)
            {
                throw new InvalidDataException("organizerKey is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.OrganizerKey = organizerKey;
            }
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new InvalidDataException("firstName is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.FirstName = firstName;
            }
            // to ensure "products" is required (not null)
            if (products == null)
            {
                throw new InvalidDataException("products is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.Products = products;
            }
            // to ensure "maxNumAttendeesAllowed" is required (not null)
            if (maxNumAttendeesAllowed == null)
            {
                throw new InvalidDataException("maxNumAttendeesAllowed is a required property for OrganizerByGroup and cannot be null");
            }
            else
            {
                this.MaxNumAttendeesAllowed = maxNumAttendeesAllowed;
            }
        }
        
        /// <summary>
        /// The organizer&#39;s surname
        /// </summary>
        /// <value>The organizer&#39;s surname</value>
        [DataMember(Name="lastName", EmitDefaultValue=false)]
        public string LastName { get; set; }

        /// <summary>
        /// The key of the group
        /// </summary>
        /// <value>The key of the group</value>
        [DataMember(Name="groupId", EmitDefaultValue=false)]
        public long? GroupId { get; set; }

        /// <summary>
        /// The name of the group
        /// </summary>
        /// <value>The name of the group</value>
        [DataMember(Name="groupName", EmitDefaultValue=false)]
        public string GroupName { get; set; }


        /// <summary>
        /// The organizer&#39;s email address
        /// </summary>
        /// <value>The organizer&#39;s email address</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// The key of the organizer
        /// </summary>
        /// <value>The key of the organizer</value>
        [DataMember(Name="organizerKey", EmitDefaultValue=false)]
        public long? OrganizerKey { get; set; }

        /// <summary>
        /// The organizer&#39;s first name
        /// </summary>
        /// <value>The organizer&#39;s first name</value>
        [DataMember(Name="firstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// The products the organizer has access to, can be &#39;G2M&#39;, &#39;G2W&#39;, &#39;G2T&#39; or &#39;OPENVOICE&#39;
        /// </summary>
        /// <value>The products the organizer has access to, can be &#39;G2M&#39;, &#39;G2W&#39;, &#39;G2T&#39; or &#39;OPENVOICE&#39;</value>
        [DataMember(Name="products", EmitDefaultValue=false)]
        public List<Product> Products { get; set; }

        /// <summary>
        /// The maximum number of attendees allowed at sessions held by this organizer
        /// </summary>
        /// <value>The maximum number of attendees allowed at sessions held by this organizer</value>
        [DataMember(Name="maxNumAttendeesAllowed", EmitDefaultValue=false)]
        public int? MaxNumAttendeesAllowed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrganizerByGroup {\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  GroupId: ").Append(GroupId).Append("\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  OrganizerKey: ").Append(OrganizerKey).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  Products: ").Append(Products).Append("\n");
            sb.Append("  MaxNumAttendeesAllowed: ").Append(MaxNumAttendeesAllowed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrganizerByGroup);
        }

        /// <summary>
        /// Returns true if OrganizerByGroup instances are equal
        /// </summary>
        /// <param name="input">Instance of OrganizerByGroup to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrganizerByGroup input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.GroupId == input.GroupId ||
                    (this.GroupId != null &&
                    this.GroupId.Equals(input.GroupId))
                ) && 
                (
                    this.GroupName == input.GroupName ||
                    (this.GroupName != null &&
                    this.GroupName.Equals(input.GroupName))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.OrganizerKey == input.OrganizerKey ||
                    (this.OrganizerKey != null &&
                    this.OrganizerKey.Equals(input.OrganizerKey))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.Products == input.Products ||
                    this.Products != null &&
                    this.Products.SequenceEqual(input.Products)
                ) && 
                (
                    this.MaxNumAttendeesAllowed == input.MaxNumAttendeesAllowed ||
                    (this.MaxNumAttendeesAllowed != null &&
                    this.MaxNumAttendeesAllowed.Equals(input.MaxNumAttendeesAllowed))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.GroupId != null)
                    hashCode = hashCode * 59 + this.GroupId.GetHashCode();
                if (this.GroupName != null)
                    hashCode = hashCode * 59 + this.GroupName.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.OrganizerKey != null)
                    hashCode = hashCode * 59 + this.OrganizerKey.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.Products != null)
                    hashCode = hashCode * 59 + this.Products.GetHashCode();
                if (this.MaxNumAttendeesAllowed != null)
                    hashCode = hashCode * 59 + this.MaxNumAttendeesAllowed.GetHashCode();
                return hashCode;
            }
        }
    }

}
