/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// The products the organizer has access to, can be &#39;G2M&#39;, &#39;G2W&#39;, &#39;G2T&#39; or &#39;OPENVOICE&#39;
    /// </summary>
    /// <value>The products the organizer has access to, can be &#39;G2M&#39;, &#39;G2W&#39;, &#39;G2T&#39; or &#39;OPENVOICE&#39;</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Product
    {
        
        /// <summary>
        /// Enum G2M for value: G2M
        /// </summary>
        [EnumMember(Value = "G2M")]
        G2M = 1,
        
        /// <summary>
        /// Enum G2T for value: G2T
        /// </summary>
        [EnumMember(Value = "G2T")]
        G2T = 2,
        
        /// <summary>
        /// Enum G2W for value: G2W
        /// </summary>
        [EnumMember(Value = "G2W")]
        G2W = 3,
        
        /// <summary>
        /// Enum OPENVOICE for value: OPENVOICE
        /// </summary>
        [EnumMember(Value = "OPENVOICE")]
        OPENVOICE = 4
    }

}
