/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes a meeting scheduled by an organizer within a specified group.
    /// </summary>
    [DataContract]
    public partial class ScheduledMeetingByGroup :  IEquatable<ScheduledMeetingByGroup>
    {
        /// <summary>
        /// The meeting type
        /// </summary>
        /// <value>The meeting type</value>
        [DataMember(Name="meetingType", EmitDefaultValue=false)]
        public MeetingType MeetingType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledMeetingByGroup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduledMeetingByGroup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledMeetingByGroup" /> class.
        /// </summary>
        /// <param name="organizerkey">The key of the meeting organizer. Field retained for backwards compatibility reasons. (required).</param>
        /// <param name="attendees">Not in use. (required).</param>
        /// <param name="lastName">The surname of the meeting organizer. (required).</param>
        /// <param name="groupName">The name of the group. (required).</param>
        /// <param name="passwordRequired">Indicates whether a password is required to join the meeting. (required).</param>
        /// <param name="email">The email address of the meeting organizer. (required).</param>
        /// <param name="subject">The subject of the meeting. (required).</param>
        /// <param name="meetingId">The meeting ID. (required).</param>
        /// <param name="organizerKey">The key of the meeting organizer. (required).</param>
        /// <param name="meetingType">The meeting type (required).</param>
        /// <param name="firstName">The first name of the meeting organizer. (required).</param>
        /// <param name="conferenceCallInfo">Audio options for the meeting. (required).</param>
        public ScheduledMeetingByGroup(long? organizerkey = default(long?), string attendees = default(string), string lastName = default(string), string groupName = default(string), bool? passwordRequired = default(bool?), string email = default(string), string subject = default(string), string meetingId = default(string), string organizerKey = default(string), MeetingType meetingType = default(MeetingType), string firstName = default(string), string conferenceCallInfo = default(string))
        {
            // to ensure "organizerkey" is required (not null)
            if (organizerkey == null)
            {
                throw new InvalidDataException("organizerkey is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.Organizerkey = organizerkey;
            }
            // to ensure "attendees" is required (not null)
            if (attendees == null)
            {
                throw new InvalidDataException("attendees is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.Attendees = attendees;
            }
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new InvalidDataException("lastName is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.LastName = lastName;
            }
            // to ensure "groupName" is required (not null)
            if (groupName == null)
            {
                throw new InvalidDataException("groupName is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.GroupName = groupName;
            }
            // to ensure "passwordRequired" is required (not null)
            if (passwordRequired == null)
            {
                throw new InvalidDataException("passwordRequired is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.PasswordRequired = passwordRequired;
            }
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new InvalidDataException("subject is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.Subject = subject;
            }
            // to ensure "meetingId" is required (not null)
            if (meetingId == null)
            {
                throw new InvalidDataException("meetingId is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.MeetingId = meetingId;
            }
            // to ensure "organizerKey" is required (not null)
            if (organizerKey == null)
            {
                throw new InvalidDataException("organizerKey is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.OrganizerKey = organizerKey;
            }
            // to ensure "meetingType" is required (not null)
            if (meetingType == null)
            {
                throw new InvalidDataException("meetingType is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.MeetingType = meetingType;
            }
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new InvalidDataException("firstName is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.FirstName = firstName;
            }
            // to ensure "conferenceCallInfo" is required (not null)
            if (conferenceCallInfo == null)
            {
                throw new InvalidDataException("conferenceCallInfo is a required property for ScheduledMeetingByGroup and cannot be null");
            }
            else
            {
                this.ConferenceCallInfo = conferenceCallInfo;
            }
        }
        
        /// <summary>
        /// The key of the meeting organizer. Field retained for backwards compatibility reasons.
        /// </summary>
        /// <value>The key of the meeting organizer. Field retained for backwards compatibility reasons.</value>
        [DataMember(Name="organizerkey", EmitDefaultValue=false)]
        public long? Organizerkey { get; set; }

        /// <summary>
        /// Not in use.
        /// </summary>
        /// <value>Not in use.</value>
        [DataMember(Name="attendees", EmitDefaultValue=false)]
        public string Attendees { get; set; }

        /// <summary>
        /// The surname of the meeting organizer.
        /// </summary>
        /// <value>The surname of the meeting organizer.</value>
        [DataMember(Name="lastName", EmitDefaultValue=false)]
        public string LastName { get; set; }

        /// <summary>
        /// The name of the group.
        /// </summary>
        /// <value>The name of the group.</value>
        [DataMember(Name="groupName", EmitDefaultValue=false)]
        public string GroupName { get; set; }

        /// <summary>
        /// Indicates whether a password is required to join the meeting.
        /// </summary>
        /// <value>Indicates whether a password is required to join the meeting.</value>
        [DataMember(Name="passwordRequired", EmitDefaultValue=false)]
        public bool? PasswordRequired { get; set; }

        /// <summary>
        /// The email address of the meeting organizer.
        /// </summary>
        /// <value>The email address of the meeting organizer.</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// The subject of the meeting.
        /// </summary>
        /// <value>The subject of the meeting.</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// The meeting ID.
        /// </summary>
        /// <value>The meeting ID.</value>
        [DataMember(Name="meetingId", EmitDefaultValue=false)]
        public string MeetingId { get; set; }

        /// <summary>
        /// The key of the meeting organizer.
        /// </summary>
        /// <value>The key of the meeting organizer.</value>
        [DataMember(Name="organizerKey", EmitDefaultValue=false)]
        public string OrganizerKey { get; set; }


        /// <summary>
        /// The first name of the meeting organizer.
        /// </summary>
        /// <value>The first name of the meeting organizer.</value>
        [DataMember(Name="firstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// Audio options for the meeting.
        /// </summary>
        /// <value>Audio options for the meeting.</value>
        [DataMember(Name="conferenceCallInfo", EmitDefaultValue=false)]
        public string ConferenceCallInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScheduledMeetingByGroup {\n");
            sb.Append("  Organizerkey: ").Append(Organizerkey).Append("\n");
            sb.Append("  Attendees: ").Append(Attendees).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("  PasswordRequired: ").Append(PasswordRequired).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  MeetingId: ").Append(MeetingId).Append("\n");
            sb.Append("  OrganizerKey: ").Append(OrganizerKey).Append("\n");
            sb.Append("  MeetingType: ").Append(MeetingType).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  ConferenceCallInfo: ").Append(ConferenceCallInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduledMeetingByGroup);
        }

        /// <summary>
        /// Returns true if ScheduledMeetingByGroup instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduledMeetingByGroup to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduledMeetingByGroup input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Organizerkey == input.Organizerkey ||
                    (this.Organizerkey != null &&
                    this.Organizerkey.Equals(input.Organizerkey))
                ) && 
                (
                    this.Attendees == input.Attendees ||
                    (this.Attendees != null &&
                    this.Attendees.Equals(input.Attendees))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.GroupName == input.GroupName ||
                    (this.GroupName != null &&
                    this.GroupName.Equals(input.GroupName))
                ) && 
                (
                    this.PasswordRequired == input.PasswordRequired ||
                    (this.PasswordRequired != null &&
                    this.PasswordRequired.Equals(input.PasswordRequired))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.MeetingId == input.MeetingId ||
                    (this.MeetingId != null &&
                    this.MeetingId.Equals(input.MeetingId))
                ) && 
                (
                    this.OrganizerKey == input.OrganizerKey ||
                    (this.OrganizerKey != null &&
                    this.OrganizerKey.Equals(input.OrganizerKey))
                ) && 
                (
                    this.MeetingType == input.MeetingType ||
                    (this.MeetingType != null &&
                    this.MeetingType.Equals(input.MeetingType))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.ConferenceCallInfo == input.ConferenceCallInfo ||
                    (this.ConferenceCallInfo != null &&
                    this.ConferenceCallInfo.Equals(input.ConferenceCallInfo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Organizerkey != null)
                    hashCode = hashCode * 59 + this.Organizerkey.GetHashCode();
                if (this.Attendees != null)
                    hashCode = hashCode * 59 + this.Attendees.GetHashCode();
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.GroupName != null)
                    hashCode = hashCode * 59 + this.GroupName.GetHashCode();
                if (this.PasswordRequired != null)
                    hashCode = hashCode * 59 + this.PasswordRequired.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.MeetingId != null)
                    hashCode = hashCode * 59 + this.MeetingId.GetHashCode();
                if (this.OrganizerKey != null)
                    hashCode = hashCode * 59 + this.OrganizerKey.GetHashCode();
                if (this.MeetingType != null)
                    hashCode = hashCode * 59 + this.MeetingType.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.ConferenceCallInfo != null)
                    hashCode = hashCode * 59 + this.ConferenceCallInfo.GetHashCode();
                return hashCode;
            }
        }
    }

}
