/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Host URL that can be used to start a meeting
    /// </summary>
    [DataContract]
    public partial class StartUrl :  IEquatable<StartUrl>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StartUrl" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StartUrl() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StartUrl" /> class.
        /// </summary>
        /// <param name="hostURL">The host URL that can be used to start a meeting. (required).</param>
        public StartUrl(string hostURL = default(string))
        {
            // to ensure "hostURL" is required (not null)
            if (hostURL == null)
            {
                throw new InvalidDataException("hostURL is a required property for StartUrl and cannot be null");
            }
            else
            {
                this.HostURL = hostURL;
            }
        }
        
        /// <summary>
        /// The host URL that can be used to start a meeting.
        /// </summary>
        /// <value>The host URL that can be used to start a meeting.</value>
        [DataMember(Name="hostURL", EmitDefaultValue=false)]
        public string HostURL { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StartUrl {\n");
            sb.Append("  HostURL: ").Append(HostURL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StartUrl);
        }

        /// <summary>
        /// Returns true if StartUrl instances are equal
        /// </summary>
        /// <param name="input">Instance of StartUrl to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StartUrl input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.HostURL == input.HostURL ||
                    (this.HostURL != null &&
                    this.HostURL.Equals(input.HostURL))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HostURL != null)
                    hashCode = hashCode * 59 + this.HostURL.GetHashCode();
                return hashCode;
            }
        }
    }

}
