/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// The status of an organizer (or group), i.e. whether the organizer (or the members of the group respectively) are able to host meetings
    /// </summary>
    /// <value>The status of an organizer (or group), i.e. whether the organizer (or the members of the group respectively) are able to host meetings</value>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status
    {
        
        /// <summary>
        /// Enum Active for value: active
        /// </summary>
        [EnumMember(Value = "active")]
        Active = 1,
        
        /// <summary>
        /// Enum Suspended for value: suspended
        /// </summary>
        [EnumMember(Value = "suspended")]
        Suspended = 2
    }

}
