/* 
 * GoToMeeting REST API
 *
 * <br>The GoToMeeting API provides seamless integration of GoToMeeting provisioning and meeting management into your existing infrastructure or third party applications.<br><br>For customers, the ability to add, suspend or delete an organizer in your GoToMeeting Corporate account from within your primary management systems simplifies and streamlines the entire process of account management. The ability to monitor meeting schedules, history and active meeting status allows managers to leverage GoToMeeting activities through your primary applications.<br><br>For third parties, the ability to create, update or delete a meeting from within your application makes real-time collaboration possible for your customers. The ability to update meeting schedules, view history and scheduled meetings, and view attendees from past meetings allows you to enhance your users' experience and the value of your applications.
 *
 * OpenAPI spec version: 1.0
 * Contact: developer-support@logmein.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PI.GTM.API.Model
{
    /// <summary>
    /// Describes an upcoming meeting of a group.
    /// </summary>
    [DataContract]
    public partial class UpcomingMeetingByGroup :  IEquatable<UpcomingMeetingByGroup>
    {
        /// <summary>
        /// DEPRECATED. This status flag is always set to &#39;INACTIVE&#39;. It exists for backwards compatibility reasons only
        /// </summary>
        /// <value>DEPRECATED. This status flag is always set to &#39;INACTIVE&#39;. It exists for backwards compatibility reasons only</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public MeetingStatus? Status { get; set; }
        /// <summary>
        /// The meeting type
        /// </summary>
        /// <value>The meeting type</value>
        [DataMember(Name="meetingType", EmitDefaultValue=false)]
        public MeetingType MeetingType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpcomingMeetingByGroup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpcomingMeetingByGroup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpcomingMeetingByGroup" /> class.
        /// </summary>
        /// <param name="startTime">The time the meeting instance will start (required).</param>
        /// <param name="lastName">The surname of the meeting organizer (required).</param>
        /// <param name="accountKey">The key of the company account (required).</param>
        /// <param name="passwordRequired">Indicates whether a password is required to join the meeting or not (required).</param>
        /// <param name="email">The meeting organizer&#39;s email address (required).</param>
        /// <param name="status">DEPRECATED. This status flag is always set to &#39;INACTIVE&#39;. It exists for backwards compatibility reasons only.</param>
        /// <param name="subject">The subject of the meeting (required).</param>
        /// <param name="locale">The current language setting of the organizer in the web portal (required).</param>
        /// <param name="organizerKey">The key of the meeting organizer (required).</param>
        /// <param name="meetingId">The meeting ID (required).</param>
        /// <param name="meetingType">The meeting type (required).</param>
        /// <param name="firstName">The meeting organizer&#39;s first name (required).</param>
        /// <param name="endTime">The time the meeting instance ended (required).</param>
        /// <param name="groupName">The name of the group the meeting belongs to (required).</param>
        public UpcomingMeetingByGroup(DateTime? startTime = default(DateTime?), string lastName = default(string), string accountKey = default(string), bool? passwordRequired = default(bool?), string email = default(string), MeetingStatus? status = default(MeetingStatus?), string subject = default(string), string locale = default(string), string organizerKey = default(string), string meetingId = default(string), MeetingType meetingType = default(MeetingType), string firstName = default(string), DateTime? endTime = default(DateTime?), string groupName = default(string))
        {
            // to ensure "startTime" is required (not null)
            if (startTime == null)
            {
                throw new InvalidDataException("startTime is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.StartTime = startTime;
            }
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new InvalidDataException("lastName is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.LastName = lastName;
            }
            // to ensure "accountKey" is required (not null)
            if (accountKey == null)
            {
                throw new InvalidDataException("accountKey is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.AccountKey = accountKey;
            }
            // to ensure "passwordRequired" is required (not null)
            if (passwordRequired == null)
            {
                throw new InvalidDataException("passwordRequired is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.PasswordRequired = passwordRequired;
            }
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new InvalidDataException("subject is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.Subject = subject;
            }
            // to ensure "locale" is required (not null)
            if (locale == null)
            {
                throw new InvalidDataException("locale is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.Locale = locale;
            }
            // to ensure "organizerKey" is required (not null)
            if (organizerKey == null)
            {
                throw new InvalidDataException("organizerKey is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.OrganizerKey = organizerKey;
            }
            // to ensure "meetingId" is required (not null)
            if (meetingId == null)
            {
                throw new InvalidDataException("meetingId is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.MeetingId = meetingId;
            }
            // to ensure "meetingType" is required (not null)
            if (meetingType == null)
            {
                throw new InvalidDataException("meetingType is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.MeetingType = meetingType;
            }
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new InvalidDataException("firstName is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.FirstName = firstName;
            }
            // to ensure "endTime" is required (not null)
            if (endTime == null)
            {
                throw new InvalidDataException("endTime is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.EndTime = endTime;
            }
            // to ensure "groupName" is required (not null)
            if (groupName == null)
            {
                throw new InvalidDataException("groupName is a required property for UpcomingMeetingByGroup and cannot be null");
            }
            else
            {
                this.GroupName = groupName;
            }
            this.Status = status;
        }
        
        /// <summary>
        /// The time the meeting instance will start
        /// </summary>
        /// <value>The time the meeting instance will start</value>
        [DataMember(Name="startTime", EmitDefaultValue=false)]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// The surname of the meeting organizer
        /// </summary>
        /// <value>The surname of the meeting organizer</value>
        [DataMember(Name="lastName", EmitDefaultValue=false)]
        public string LastName { get; set; }

        /// <summary>
        /// The key of the company account
        /// </summary>
        /// <value>The key of the company account</value>
        [DataMember(Name="accountKey", EmitDefaultValue=false)]
        public string AccountKey { get; set; }

        /// <summary>
        /// Indicates whether a password is required to join the meeting or not
        /// </summary>
        /// <value>Indicates whether a password is required to join the meeting or not</value>
        [DataMember(Name="passwordRequired", EmitDefaultValue=false)]
        public bool? PasswordRequired { get; set; }

        /// <summary>
        /// The meeting organizer&#39;s email address
        /// </summary>
        /// <value>The meeting organizer&#39;s email address</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }


        /// <summary>
        /// The subject of the meeting
        /// </summary>
        /// <value>The subject of the meeting</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// The current language setting of the organizer in the web portal
        /// </summary>
        /// <value>The current language setting of the organizer in the web portal</value>
        [DataMember(Name="locale", EmitDefaultValue=false)]
        public string Locale { get; set; }

        /// <summary>
        /// The key of the meeting organizer
        /// </summary>
        /// <value>The key of the meeting organizer</value>
        [DataMember(Name="organizerKey", EmitDefaultValue=false)]
        public string OrganizerKey { get; set; }

        /// <summary>
        /// The meeting ID
        /// </summary>
        /// <value>The meeting ID</value>
        [DataMember(Name="meetingId", EmitDefaultValue=false)]
        public string MeetingId { get; set; }


        /// <summary>
        /// The meeting organizer&#39;s first name
        /// </summary>
        /// <value>The meeting organizer&#39;s first name</value>
        [DataMember(Name="firstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// The time the meeting instance ended
        /// </summary>
        /// <value>The time the meeting instance ended</value>
        [DataMember(Name="endTime", EmitDefaultValue=false)]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// The name of the group the meeting belongs to
        /// </summary>
        /// <value>The name of the group the meeting belongs to</value>
        [DataMember(Name="groupName", EmitDefaultValue=false)]
        public string GroupName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpcomingMeetingByGroup {\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  AccountKey: ").Append(AccountKey).Append("\n");
            sb.Append("  PasswordRequired: ").Append(PasswordRequired).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  OrganizerKey: ").Append(OrganizerKey).Append("\n");
            sb.Append("  MeetingId: ").Append(MeetingId).Append("\n");
            sb.Append("  MeetingType: ").Append(MeetingType).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpcomingMeetingByGroup);
        }

        /// <summary>
        /// Returns true if UpcomingMeetingByGroup instances are equal
        /// </summary>
        /// <param name="input">Instance of UpcomingMeetingByGroup to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpcomingMeetingByGroup input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.AccountKey == input.AccountKey ||
                    (this.AccountKey != null &&
                    this.AccountKey.Equals(input.AccountKey))
                ) && 
                (
                    this.PasswordRequired == input.PasswordRequired ||
                    (this.PasswordRequired != null &&
                    this.PasswordRequired.Equals(input.PasswordRequired))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.Locale == input.Locale ||
                    (this.Locale != null &&
                    this.Locale.Equals(input.Locale))
                ) && 
                (
                    this.OrganizerKey == input.OrganizerKey ||
                    (this.OrganizerKey != null &&
                    this.OrganizerKey.Equals(input.OrganizerKey))
                ) && 
                (
                    this.MeetingId == input.MeetingId ||
                    (this.MeetingId != null &&
                    this.MeetingId.Equals(input.MeetingId))
                ) && 
                (
                    this.MeetingType == input.MeetingType ||
                    (this.MeetingType != null &&
                    this.MeetingType.Equals(input.MeetingType))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.EndTime == input.EndTime ||
                    (this.EndTime != null &&
                    this.EndTime.Equals(input.EndTime))
                ) && 
                (
                    this.GroupName == input.GroupName ||
                    (this.GroupName != null &&
                    this.GroupName.Equals(input.GroupName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StartTime != null)
                    hashCode = hashCode * 59 + this.StartTime.GetHashCode();
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.AccountKey != null)
                    hashCode = hashCode * 59 + this.AccountKey.GetHashCode();
                if (this.PasswordRequired != null)
                    hashCode = hashCode * 59 + this.PasswordRequired.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.Locale != null)
                    hashCode = hashCode * 59 + this.Locale.GetHashCode();
                if (this.OrganizerKey != null)
                    hashCode = hashCode * 59 + this.OrganizerKey.GetHashCode();
                if (this.MeetingId != null)
                    hashCode = hashCode * 59 + this.MeetingId.GetHashCode();
                if (this.MeetingType != null)
                    hashCode = hashCode * 59 + this.MeetingType.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.EndTime != null)
                    hashCode = hashCode * 59 + this.EndTime.GetHashCode();
                if (this.GroupName != null)
                    hashCode = hashCode * 59 + this.GroupName.GetHashCode();
                return hashCode;
            }
        }
    }

}
